// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_hud_types.proto

#include "dota_hud_types.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_dota_5fhud_5ftypes_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dota_5fhud_5ftypes_2eproto = nullptr;
const uint32_t TableStruct_dota_5fhud_5ftypes_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_dota_5fhud_5ftypes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024dota_hud_types.proto\032 google/protobuf/"
  "descriptor.proto*\357\022\n\022EHeroSelectionText\022"
  ")\n\034k_EHeroSelectionText_Invalid\020\377\377\377\377\377\377\377\377"
  "\377\001\022\035\n\031k_EHeroSelectionText_None\020\000\022H\n\037k_E"
  "HeroSelectionText_ChooseHero\020\001\032#\252\324\030\037#DOT"
  "A_Hero_Selection_ChooseHero\022h\n/k_EHeroSe"
  "lectionText_AllDraft_Planning_YouFirst\020\002"
  "\0323\252\324\030/#DOTA_Hero_Selection_AllDraft_Plan"
  "ning_YouFirst\022j\n0k_EHeroSelectionText_Al"
  "lDraft_Planning_TheyFirst\020\003\0324\252\324\0300#DOTA_H"
  "ero_Selection_AllDraft_Planning_TheyFirs"
  "t\022\\\n%k_EHeroSelectionText_AllDraft_Banni"
  "ng\020\004\0321\252\324\030-#DOTA_Hero_Selection_AllPick_B"
  "anning_Nominate\022a\n)k_EHeroSelectionText_"
  "AllDraft_Ban_Waiting\020\005\0322\252\324\030.#DOTA_Hero_S"
  "election_AllPick_Banning_Nominated\022]\n%k_"
  "EHeroSelectionText_AllDraft_PickTwo\020\006\0322\252"
  "\324\030.#DOTA_Hero_Selection_AllPick_PickPhas"
  "e_PickTwo\022e\n)k_EHeroSelectionText_AllDra"
  "ft_PickOneMore\020\007\0326\252\324\0302#DOTA_Hero_Selecti"
  "on_AllPick_PickPhase_PickOneMore\022]\n%k_EH"
  "eroSelectionText_AllDraft_PickOne\020\010\0322\252\324\030"
  ".#DOTA_Hero_Selection_AllPick_PickPhase_"
  "PickOne\022k\n,k_EHeroSelectionText_AllDraft"
  "_WaitingRadiant\020\t\0329\252\324\0305#DOTA_Hero_Select"
  "ion_AllPick_PickPhase_WaitingRadiant\022e\n)"
  "k_EHeroSelectionText_AllDraft_WaitingDir"
  "e\020\n\0326\252\324\0302#DOTA_Hero_Selection_AllPick_Pi"
  "ckPhase_WaitingDire\022o\n.k_EHeroSelectionT"
  "ext_AllDraft_TeammateRandomed\020\013\032;\252\324\0307#DO"
  "TA_Hero_Selection_AllDraft_TeammateRando"
  "med_Panorama\022p\n3k_EHeroSelectionText_All"
  "Draft_YouPicking_LosingGold\020\014\0327\252\324\0303#DOTA"
  "_Hero_Selection_AllDraft_YouPicking_Losi"
  "ngGold\022r\n4k_EHeroSelectionText_AllDraft_"
  "TheyPicking_LosingGold\020\r\0328\252\324\0304#DOTA_Hero"
  "_Selection_AllDraft_TheyPicking_LosingGo"
  "ld\022h\n/k_EHeroSelectionText_CaptainsMode_"
  "ChooseCaptain\020\016\0323\252\324\030/#DOTA_Hero_Selectio"
  "n_CaptainsMode_ChooseCaptain\022|\n9k_EHeroS"
  "electionText_CaptainsMode_WaitingForChoo"
  "seCaptain\020\017\032=\252\324\0309#DOTA_Hero_Selection_Ca"
  "ptainsMode_WaitingForChooseCaptain\022`\n+k_"
  "EHeroSelectionText_CaptainsMode_YouSelec"
  "t\020\020\032/\252\324\030+#DOTA_Hero_Selection_CaptainsMo"
  "de_YouSelect\022b\n,k_EHeroSelectionText_Cap"
  "tainsMode_TheySelect\020\021\0320\252\324\030,#DOTA_Hero_S"
  "election_CaptainsMode_TheySelect\022Z\n(k_EH"
  "eroSelectionText_CaptainsMode_YouBan\020\022\032,"
  "\252\324\030(#DOTA_Hero_Selection_CaptainsMode_Yo"
  "uBan\022\\\n)k_EHeroSelectionText_CaptainsMod"
  "e_TheyBan\020\023\032-\252\324\030)#DOTA_Hero_Selection_Ca"
  "ptainsMode_TheyBan\022`\n+k_EHeroSelectionTe"
  "xt_RandomDraft_HeroReview\020\024\032/\252\324\030+#DOTA_H"
  "ero_Selection_RandomDraft_HeroReview\022a\n-"
  "k_EHeroSelectionText_RandomDraft_RoundDi"
  "splay\020\025\032.\252\324\030*#DOTA_Hero_Selection_AllDra"
  "ft_RoundDisplay\022W\n(k_EHeroSelectionText_"
  "RandomDraft_Waiting\020\026\032)\252\324\030%#DOTA_Hero_Se"
  "lection_AllDraft_Waiting\022X\n\'k_EHeroSelec"
  "tionText_EventGame_BanPhase\020\027\032+\252\324\030\'#DOTA"
  "_Hero_Selection_EventGame_BanPhase:\?\n\022hu"
  "d_localize_token\022!.google.protobuf.EnumV"
  "alueOptions\030\305\212\003 \001(\t"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_dota_5fhud_5ftypes_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_dota_5fhud_5ftypes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dota_5fhud_5ftypes_2eproto = {
    false, false, 2539, descriptor_table_protodef_dota_5fhud_5ftypes_2eproto,
    "dota_hud_types.proto",
    &descriptor_table_dota_5fhud_5ftypes_2eproto_once, descriptor_table_dota_5fhud_5ftypes_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_dota_5fhud_5ftypes_2eproto::offsets,
    nullptr, file_level_enum_descriptors_dota_5fhud_5ftypes_2eproto,
    file_level_service_descriptors_dota_5fhud_5ftypes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dota_5fhud_5ftypes_2eproto_getter() {
  return &descriptor_table_dota_5fhud_5ftypes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dota_5fhud_5ftypes_2eproto(&descriptor_table_dota_5fhud_5ftypes_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHeroSelectionText_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dota_5fhud_5ftypes_2eproto);
  return file_level_enum_descriptors_dota_5fhud_5ftypes_2eproto[0];
}
bool EHeroSelectionText_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const std::string hud_localize_token_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  hud_localize_token(kHudLocalizeTokenFieldNumber, hud_localize_token_default, nullptr);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
