// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: valveextensions.proto

#include "valveextensions.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_valveextensions_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_valveextensions_2eproto = nullptr;
const uint32_t TableStruct_valveextensions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_valveextensions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025valveextensions.proto\032 google/protobuf"
  "/descriptor.proto:9\n\tmap_field\022\035.google."
  "protobuf.FieldOptions\030\310\334\003 \001(\010:\005false:7\n\007"
  "map_key\022\035.google.protobuf.FieldOptions\030\311"
  "\334\003 \001(\010:\005false:=\n\021diff_encode_field\022\035.goo"
  "gle.protobuf.FieldOptions\030\312\334\003 \001(\005:\0010:<\n\014"
  "delta_ignore\022\035.google.protobuf.FieldOpti"
  "ons\030\313\334\003 \001(\010:\005false:\?\n\023steamml_max_entrie"
  "s\022\035.google.protobuf.FieldOptions\030\314\334\003 \001(\r"
  ":\0010:D\n\024steamml_is_timestamp\022\035.google.pro"
  "tobuf.FieldOptions\030\315\334\003 \001(\010:\005false:<\n\020ste"
  "amlearn_count\022\035.google.protobuf.FieldOpt"
  "ions\030\316\334\003 \001(\r:\0010:@\n\024schema_friendly_name\022"
  "!.google.protobuf.EnumValueOptions\030\350\007 \001("
  "\t:>\n\022schema_description\022!.google.protobu"
  "f.EnumValueOptions\030\351\007 \001(\t:F\n\032schema_supp"
  "ress_enumerator\022!.google.protobuf.EnumVa"
  "lueOptions\030\352\007 \001(\010"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_valveextensions_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_valveextensions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_valveextensions_2eproto = {
    false, false, 697, descriptor_table_protodef_valveextensions_2eproto,
    "valveextensions.proto",
    &descriptor_table_valveextensions_2eproto_once, descriptor_table_valveextensions_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_valveextensions_2eproto::offsets,
    nullptr, file_level_enum_descriptors_valveextensions_2eproto,
    file_level_service_descriptors_valveextensions_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_valveextensions_2eproto_getter() {
  return &descriptor_table_valveextensions_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_valveextensions_2eproto(&descriptor_table_valveextensions_2eproto);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  map_field(kMapFieldFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  map_key(kMapKeyFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int32_t >, 5, false>
  diff_encode_field(kDiffEncodeFieldFieldNumber, 0, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  delta_ignore(kDeltaIgnoreFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  steamml_max_entries(kSteammlMaxEntriesFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  steamml_is_timestamp(kSteammlIsTimestampFieldNumber, false, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  steamlearn_count(kSteamlearnCountFieldNumber, 0u, nullptr);
const std::string schema_friendly_name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  schema_friendly_name(kSchemaFriendlyNameFieldNumber, schema_friendly_name_default, nullptr);
const std::string schema_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  schema_description(kSchemaDescriptionFieldNumber, schema_description_default, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  schema_suppress_enumerator(kSchemaSuppressEnumeratorFieldNumber, false, nullptr);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
