#pragma once


//enum DotaUnitType : int {
//	DOTA_UNIT_NONE = 0,
//	DOTA_UNIT_HERO,
//	DOTA_UNIT_STRUCTURE,
//	DOTA_UNIT_TOWER,
//	DOTA_UNIT_ANCIENT,
//	DOTA_UNIT_BARRACKS,
//	DOTA_UNIT_CREEP,
//	DOTA_UNIT_COURIER,
//	DOTA_UNIT_LANE_CREEP,
//	DOTA_UNIT_ROSHAN,
//	DOTA_UNIT_SHOPKEEP
//};

enum class DotaRunes : int {
	INVALID = -1,
	DOUBLEDAMAGE = 0,
	HASTE = 1,
	ILLUSION = 2,
	INVISIBILITY = 3,
	REGENERATION = 4,
	BOUNTY = 5,
	COUNT = 6, //???
	WATER = 7
};


//what units will receive the PrepareUnitOrders() command
enum PlayerOrderIssuer_t : int {
	DOTA_ORDER_ISSUER_SELECTED_UNITS = 0,
	DOTA_ORDER_ISSUER_CURRENT_UNIT_ONLY = 1,
	DOTA_ORDER_ISSUER_HERO_ONLY = 2,
	DOTA_ORDER_ISSUER_PASSED_UNIT_ONLY = 3
};
