#pragma once
#include <cstdint>
namespace Netvars {
	namespace C_BaseCombatCharacter {
		constexpr uint32_t m_hMyWearables = 0x958; // C_NetworkUtlVectorBase< CHandle< C_EconWearable > >
		constexpr uint32_t m_bloodColor = 0x970; // int32
		constexpr uint32_t m_leftFootAttachment = 0x974; // AttachmentHandle_t
		constexpr uint32_t m_rightFootAttachment = 0x975; // AttachmentHandle_t
		constexpr uint32_t m_nWaterWakeMode = 0x978; // C_BaseCombatCharacter::WaterWakeMode_t
		constexpr uint32_t m_flWaterWorldZ = 0x97c; // float32
		constexpr uint32_t m_flWaterNextTraceTime = 0x980; // float32
		constexpr uint32_t m_flFieldOfView = 0x984; // float32
	}
	namespace C_BaseEntity {
		constexpr uint32_t m_CBodyComponent = 0x30; // CBodyComponent*
		constexpr uint32_t m_NetworkTransmitComponent = 0x38; // CNetworkTransmitComponent
		constexpr uint32_t m_nLastThinkTick = 0x2f8; // GameTick_t
		constexpr uint32_t m_pGameSceneNode = 0x300; // CGameSceneNode*
		constexpr uint32_t m_pRenderComponent = 0x308; // CRenderComponent*
		constexpr uint32_t m_pCollision = 0x310; // CCollisionProperty*
		constexpr uint32_t m_iMaxHealth = 0x318; // int32
		constexpr uint32_t m_iHealth = 0x31c; // int32
		constexpr uint32_t m_lifeState = 0x320; // uint8
		constexpr uint32_t m_takedamage = 0x321; // DamageOptions_t
		constexpr uint32_t m_bTakesDamage = 0x322; // bool
		constexpr uint32_t m_nTakeDamageFlags = 0x324; // TakeDamageFlags_t
		constexpr uint32_t m_ubInterpolationFrame = 0x328; // uint8
		constexpr uint32_t m_hSceneObjectController = 0x32c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_nNoInterpolationTick = 0x330; // int32
		constexpr uint32_t m_nVisibilityNoInterpolationTick = 0x334; // int32
		constexpr uint32_t m_flProxyRandomValue = 0x338; // float32
		constexpr uint32_t m_iEFlags = 0x33c; // int32
		constexpr uint32_t m_nWaterType = 0x340; // uint8
		constexpr uint32_t m_bInterpolateEvenWithNoModel = 0x341; // bool
		constexpr uint32_t m_bPredictionEligible = 0x342; // bool
		constexpr uint32_t m_bApplyLayerMatchIDToModel = 0x343; // bool
		constexpr uint32_t m_tokLayerMatchID = 0x344; // CUtlStringToken
		constexpr uint32_t m_nSubclassID = 0x348; // CUtlStringToken
		constexpr uint32_t m_nSimulationTick = 0x358; // int32
		constexpr uint32_t m_iCurrentThinkContext = 0x35c; // int32
		constexpr uint32_t m_aThinkFunctions = 0x360; // CUtlVector< thinkfunc_t >
		constexpr uint32_t m_flAnimTime = 0x378; // float32
		constexpr uint32_t m_flSimulationTime = 0x37c; // float32
		constexpr uint32_t m_nSceneObjectOverrideFlags = 0x380; // uint8
		constexpr uint32_t m_bHasSuccessfullyInterpolated = 0x381; // bool
		constexpr uint32_t m_bHasAddedVarsToInterpolation = 0x382; // bool
		constexpr uint32_t m_bRenderEvenWhenNotSuccessfullyInterpolated = 0x383; // bool
		constexpr uint32_t m_nInterpolationLatchDirtyFlags = 0x384; // int32[2]
		constexpr uint32_t m_ListEntry = 0x38c; // uint16[11]
		constexpr uint32_t m_flCreateTime = 0x3a4; // GameTime_t
		constexpr uint32_t m_flSpeed = 0x3a8; // float32
		constexpr uint32_t m_EntClientFlags = 0x3ac; // uint16
		constexpr uint32_t m_bClientSideRagdoll = 0x3ae; // bool
		constexpr uint32_t m_iTeamNum = 0x3af; // uint8
		constexpr uint32_t m_spawnflags = 0x3b0; // uint32
		constexpr uint32_t m_nNextThinkTick = 0x3b4; // GameTick_t
		constexpr uint32_t m_fFlags = 0x3b8; // uint32
		constexpr uint32_t m_vecAbsVelocity = 0x3bc; // Vector
		constexpr uint32_t m_vecVelocity = 0x3c8; // CNetworkVelocityVector
		constexpr uint32_t m_hEffectEntity = 0x3f8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hOwnerEntity = 0x3fc; // CHandle< C_BaseEntity >
		constexpr uint32_t m_MoveCollide = 0x400; // MoveCollide_t
		constexpr uint32_t m_MoveType = 0x401; // MoveType_t
		constexpr uint32_t m_flWaterLevel = 0x404; // float32
		constexpr uint32_t m_fEffects = 0x408; // uint32
		constexpr uint32_t m_hGroundEntity = 0x40c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_flFriction = 0x410; // float32
		constexpr uint32_t m_flElasticity = 0x414; // float32
		constexpr uint32_t m_flGravityScale = 0x418; // float32
		constexpr uint32_t m_flTimeScale = 0x41c; // float32
		constexpr uint32_t m_bSimulatedEveryTick = 0x420; // bool
		constexpr uint32_t m_bAnimatedEveryTick = 0x421; // bool
		constexpr uint32_t m_nMinCPULevel = 0x422; // uint8
		constexpr uint32_t m_nMaxCPULevel = 0x423; // uint8
		constexpr uint32_t m_nMinGPULevel = 0x424; // uint8
		constexpr uint32_t m_nMaxGPULevel = 0x425; // uint8
		constexpr uint32_t m_flNavIgnoreUntilTime = 0x428; // GameTime_t
		constexpr uint32_t m_hThink = 0x42c; // uint16
		constexpr uint32_t m_fBBoxVisFlags = 0x438; // uint8
		constexpr uint32_t m_bPredictable = 0x439; // bool
		constexpr uint32_t m_bRenderWithViewModels = 0x43a; // bool
		constexpr uint32_t m_nSplitUserPlayerPredictionSlot = 0x43c; // CSplitScreenSlot
		constexpr uint32_t m_nFirstPredictableCommand = 0x440; // int32
		constexpr uint32_t m_nLastPredictableCommand = 0x444; // int32
		constexpr uint32_t m_hOldMoveParent = 0x448; // CHandle< C_BaseEntity >
		constexpr uint32_t m_Particles = 0x450; // CParticleProperty
		constexpr uint32_t m_vecPredictedScriptFloats = 0x478; // CUtlVector< float32 >
		constexpr uint32_t m_vecPredictedScriptFloatIDs = 0x490; // CUtlVector< int32 >
		constexpr uint32_t m_nNextScriptVarRecordID = 0x4c0; // int32
		constexpr uint32_t m_vecAngVelocity = 0x4d0; // QAngle
		constexpr uint32_t m_DataChangeEventRef = 0x4dc; // int32
		constexpr uint32_t m_dependencies = 0x4e0; // CUtlVector< CEntityHandle >
		constexpr uint32_t m_nCreationTick = 0x4f8; // int32
		constexpr uint32_t m_bAnimTimeChanged = 0x511; // bool
		constexpr uint32_t m_bSimulationTimeChanged = 0x512; // bool
		constexpr uint32_t m_sUniqueHammerID = 0x520; // CUtlString
	}
	namespace C_DOTA_Item {
		constexpr uint32_t m_bCombinable = 0x5a0; // bool
		constexpr uint32_t m_bPermanent = 0x5a1; // bool
		constexpr uint32_t m_bStackable = 0x5a2; // bool
		constexpr uint32_t m_iStackableMax = 0x5a4; // int32
		constexpr uint32_t m_bRecipe = 0x5a8; // bool
		constexpr uint32_t m_iSharability = 0x5ac; // int32
		constexpr uint32_t m_bDroppable = 0x5b0; // bool
		constexpr uint32_t m_bPurchasable = 0x5b1; // bool
		constexpr uint32_t m_bSellable = 0x5b2; // bool
		constexpr uint32_t m_bInitiallySellable = 0x5b3; // bool
		constexpr uint32_t m_bForceUnsellable = 0x5b4; // bool
		constexpr uint32_t m_bRequiresCharges = 0x5b5; // bool
		constexpr uint32_t m_bDisplayCharges = 0x5b6; // bool
		constexpr uint32_t m_bHideCharges = 0x5b7; // bool
		constexpr uint32_t m_bKillable = 0x5b8; // bool
		constexpr uint32_t m_bGloballyCombinable = 0x5b9; // bool
		constexpr uint32_t m_bDisassemblable = 0x5ba; // bool
		constexpr uint32_t m_bIsNeutralDrop = 0x5bb; // bool
		constexpr uint32_t m_nNeutralDropTeam = 0x5bc; // int32
		constexpr uint32_t m_bAlertable = 0x5c0; // bool
		constexpr uint32_t m_iInitialCharges = 0x5c4; // int32
		constexpr uint32_t m_bCastOnPickup = 0x5c8; // bool
		constexpr uint32_t m_bOnlyPlayerHeroPickup = 0x5c9; // bool
		constexpr uint32_t m_bCreepHeroPickup = 0x5ca; // bool
		constexpr uint32_t m_iValuelessCharges = 0x5cc; // int32
		constexpr uint32_t m_iCurrentCharges = 0x5d0; // int32
		constexpr uint32_t m_iSecondaryCharges = 0x5d4; // int32
		constexpr uint32_t m_bCombineLocked = 0x5d8; // bool
		constexpr uint32_t m_flPurchaseTime = 0x5dc; // GameTime_t
		constexpr uint32_t m_flAssembledTime = 0x5e0; // GameTime_t
		constexpr uint32_t m_bPurchasedWhileDead = 0x5e4; // bool
		constexpr uint32_t m_bCanBeUsedOutOfInventory = 0x5e5; // bool
		constexpr uint32_t m_bItemEnabled = 0x5e6; // bool
		constexpr uint32_t m_flEnableTime = 0x5e8; // GameTime_t
		constexpr uint32_t m_flReclaimTime = 0x5ec; // GameTime_t
		constexpr uint32_t m_bDisplayOwnership = 0x5f0; // bool
		constexpr uint32_t m_bShowOnMinimap = 0x5f1; // bool
		constexpr uint32_t m_flMinimapIconSize = 0x5f4; // float32
		constexpr uint32_t m_bIsUpgradeable = 0x5f8; // bool
		constexpr uint32_t m_nUpgradeProgress = 0x5fc; // int32
		constexpr uint32_t m_nUpgradeGoal = 0x600; // int32
		constexpr uint32_t m_hOldOwnerEntity = 0x604; // CHandle< C_BaseEntity >
		constexpr uint32_t m_iOldCharges = 0x608; // int32
		constexpr uint32_t m_iPlayerOwnerID = 0x60c; // PlayerID_t
		constexpr uint32_t m_vecPreGameTransferPlayerIDs = 0x610; // C_NetworkUtlVectorBase< uint8 >
	}
	namespace PlayerResourcePlayerData_t {
		constexpr uint32_t m_bIsValid = 0x30; // bool
		constexpr uint32_t m_iszPlayerName = 0x38; // CUtlSymbolLarge
		constexpr uint32_t m_iPlayerTeam = 0x40; // int32
		constexpr uint32_t m_bFullyJoinedServer = 0x44; // bool
		constexpr uint32_t m_bFakeClient = 0x45; // bool
		constexpr uint32_t m_bIsBroadcaster = 0x46; // bool
		constexpr uint32_t m_iBroadcasterChannel = 0x48; // uint32
		constexpr uint32_t m_iBroadcasterChannelSlot = 0x4c; // uint32
		constexpr uint32_t m_bIsBroadcasterChannelCameraman = 0x50; // bool
		constexpr uint32_t m_iConnectionState = 0x54; // int32
		constexpr uint32_t m_iPlayerSteamID = 0x58; // uint64
		constexpr uint32_t m_eCoachTeam = 0x60; // DOTATeam_t
		constexpr uint32_t m_vecPrivateCoachPlayerIDs = 0x68; // C_NetworkUtlVectorBase< PlayerID_t >
		constexpr uint32_t m_unCoachRating = 0x80; // uint32
		constexpr uint32_t m_eLiveSpectatorTeam = 0x84; // DOTATeam_t
		constexpr uint32_t m_nLiveSpectatorSpectatedHeroIndex = 0x88; // int32
		constexpr uint32_t m_bIsPlusSubscriber = 0x8c; // bool
		constexpr uint32_t m_bWasMVPLastGame = 0x8d; // bool
		constexpr uint32_t m_nCavernCrawlMapVariant = 0x8e; // CavernCrawlMapVariant_t
		constexpr uint32_t m_eAccoladeType = 0x90; // int32[3]
		constexpr uint32_t m_unAccoladeData = 0xa0; // uint64[3]
		constexpr uint32_t m_iRankTier = 0xb8; // int32
		constexpr uint32_t m_iTitle = 0xbc; // int32
		constexpr uint32_t m_unFavTeamPacked = 0xc0; // uint64
		constexpr uint32_t m_nPlayerSlot = 0xc8; // CPlayerSlot
		constexpr uint32_t m_bIsBot = 0xcc; // bool
	}
	namespace C_DOTABaseAbility {
		constexpr uint32_t m_bAltCastState = 0x530; // bool
		constexpr uint32_t m_iEnemyLevel = 0x534; // int32
		constexpr uint32_t m_iMaxLevel = 0x538; // int32
		constexpr uint32_t m_bCanLearn = 0x53c; // bool
		constexpr uint32_t m_flUpgradeBlend = 0x540; // float32
		constexpr uint32_t m_bUpgradedDuringQuickcastPreview = 0x544; // bool
		constexpr uint32_t m_bConsiderOvershootInGetCastRange = 0x545; // bool
		constexpr uint32_t m_bRefCountsModifiers = 0x546; // bool
		constexpr uint32_t m_bHidden = 0x547; // bool
		constexpr uint32_t m_bOldHidden = 0x548; // bool
		constexpr uint32_t m_bActivated = 0x549; // bool
		constexpr uint32_t m_bOldActivated = 0x54a; // bool
		constexpr uint32_t m_nAbilityBarType = 0x54c; // AbilityBarType_t
		constexpr uint32_t m_iDirtyButtons = 0x550; // int32
		constexpr uint32_t m_bPerformDirtyParity = 0x554; // bool
		constexpr uint32_t m_iLevel = 0x558; // int32
		constexpr uint32_t m_bAbilityLevelDirty = 0x55c; // bool
		constexpr uint32_t m_bToggleState = 0x55d; // bool
		constexpr uint32_t m_flAbilityMuteDuration = 0x560; // float32
		constexpr uint32_t m_bInAbilityPhase = 0x564; // bool
		constexpr uint32_t m_fCooldown = 0x568; // float32
		constexpr uint32_t m_flCooldownLength = 0x56c; // float32
		constexpr uint32_t m_iManaCost = 0x570; // int32
		constexpr uint32_t m_bAutoCastState = 0x574; // bool
		constexpr uint32_t m_flChannelStartTime = 0x578; // GameTime_t
		constexpr uint32_t m_flCastStartTime = 0x57c; // GameTime_t
		constexpr uint32_t m_bInIndefiniteCooldown = 0x580; // bool
		constexpr uint32_t m_bFrozenCooldown = 0x581; // bool
		constexpr uint32_t m_flOverrideCastPoint = 0x584; // float32
		constexpr uint32_t m_bStolen = 0x588; // bool
		constexpr uint32_t m_bStealable = 0x589; // bool
		constexpr uint32_t m_bReplicated = 0x58a; // bool
		constexpr uint32_t m_nAbilityCurrentCharges = 0x58c; // int32
		constexpr uint32_t m_fAbilityChargeRestoreTimeRemaining = 0x590; // float32
		constexpr uint32_t m_bUpgradeRecommended = 0x594; // bool
		constexpr uint32_t m_flLastCastClickTime = 0x598; // float32
	}
	namespace C_NextBotCombatCharacter {
		constexpr uint32_t m_shadowTimer = 0x9e8; // CountdownTimer
		constexpr uint32_t m_bInFrustum = 0xa00; // bool
		constexpr uint32_t m_nInFrustumFrame = 0xa04; // int32
		constexpr uint32_t m_flFrustumDistanceSqr = 0xa08; // float32
		constexpr uint32_t m_nLod = 0xa0c; // uint8
	}
	namespace C_DOTA_BaseNPC {
		constexpr uint32_t m_bIsPhantom = 0xa20; // bool
		constexpr uint32_t m_iUnitType = 0xa24; // uint32
		constexpr uint32_t m_bSelectionRingVisible = 0xa38; // bool
		constexpr uint32_t m_iCurrentLevel = 0xa3c; // int32
		constexpr uint32_t m_bIsAncient = 0xa40; // bool
		constexpr uint32_t m_bIsBossCreature = 0xa41; // bool
		constexpr uint32_t m_bStolenScepter = 0xa42; // bool
		constexpr uint32_t m_bIsNeutralUnitType = 0xa43; // bool
		constexpr uint32_t m_bSelectOnSpawn = 0xa44; // bool
		constexpr uint32_t m_bCachedReplicatedMorphlingIllusion = 0xa45; // bool
		constexpr uint32_t m_bIgnoreAddSummonedToSelection = 0xa46; // bool
		constexpr uint32_t m_bConsideredHero = 0xa47; // bool
		constexpr uint32_t m_bUsesConstantGesture = 0xa48; // bool
		constexpr uint32_t m_bUseHeroAbilityNumbers = 0xa49; // bool
		constexpr uint32_t m_bHasSharedAbilities = 0xa4a; // bool
		constexpr uint32_t m_bIsSummoned = 0xa4b; // bool
		constexpr uint32_t m_bCanBeDominated = 0xa4c; // bool
		constexpr uint32_t m_bHasUpgradeableAbilities = 0xa4d; // bool
		constexpr uint32_t m_flHealthThinkRegen = 0xa50; // float32
		constexpr uint32_t m_iIsControllableByPlayer64 = 0xa58; // uint64
		constexpr uint32_t m_nHealthBarOffsetOverride = 0xa60; // int32
		constexpr uint32_t m_bCanRespawn = 0xa64; // bool
		constexpr uint32_t m_iAttackRange = 0xa68; // int32
		constexpr uint32_t m_iCombatClass = 0xa6c; // int32
		constexpr uint32_t m_iCombatClassAttack = 0xa70; // int32
		constexpr uint32_t m_iCombatClassDefend = 0xa74; // int32
		constexpr uint32_t m_colorGemColor = 0xa78; // Color
		constexpr uint32_t m_bHasColorGem = 0xa7c; // bool
		constexpr uint32_t m_nFXDeniableIndex = 0xa80; // ParticleIndex_t
		constexpr uint32_t m_iMoveSpeed = 0xa84; // int32
		constexpr uint32_t m_iBaseAttackSpeed = 0xa88; // int32
		constexpr uint32_t m_flBaseAttackTime = 0xa8c; // float32
		constexpr uint32_t m_iUnitNameIndex = 0xa90; // int32
		constexpr uint32_t m_iHealthBarOffset = 0xa94; // int32
		constexpr uint32_t m_iHealthBarHighlightColor = 0xa98; // Color
		constexpr uint32_t m_flMana = 0xa9c; // float32
		constexpr uint32_t m_flMaxMana = 0xaa0; // float32
		constexpr uint32_t m_flManaThinkRegen = 0xaa4; // float32
		constexpr uint32_t m_iBKBChargesUsed = 0xaa8; // int32
		constexpr uint32_t m_iAeonChargesUsed = 0xaac; // int32
		constexpr uint32_t m_flRefresherUseTime = 0xab0; // GameTime_t
		constexpr uint32_t m_flRefresherLastCooldown = 0xab4; // float32
		constexpr uint32_t m_iBotDebugData = 0xab8; // int32
		constexpr uint32_t m_bIsIllusion = 0xabc; // bool
		constexpr uint32_t m_bHasClientSeenIllusionModifier = 0xabd; // bool
		constexpr uint32_t m_hAbilities = 0xac0; // CHandle< C_BaseEntity >[35]
		constexpr uint32_t m_flInvisibilityLevel = 0xb4c; // float32
		constexpr uint32_t m_flHullRadius = 0xb50; // float32
		constexpr uint32_t m_flCollisionPadding = 0xb54; // float32
		constexpr uint32_t m_flRingRadius = 0xb58; // float32
		constexpr uint32_t m_flProjectileCollisionSize = 0xb5c; // float32
		constexpr uint32_t m_iszUnitName = 0xb60; // CUtlSymbolLarge
		constexpr uint32_t m_iszParticleFolder = 0xb68; // CUtlSymbolLarge
		constexpr uint32_t m_iszSoundSet = 0xb70; // CUtlSymbolLarge
		constexpr uint32_t m_iszSelectionGroup = 0xb78; // CUtlSymbolLarge
		constexpr uint32_t m_iszVoiceFile = 0xb80; // CUtlSymbolLarge
		constexpr uint32_t m_iszGameSoundsFile = 0xb88; // CUtlSymbolLarge
		constexpr uint32_t m_iszVoiceBackgroundSound = 0xb90; // CUtlSymbolLarge
		constexpr uint32_t m_iszIdleSoundLoop = 0xb98; // CUtlSymbolLarge
		constexpr uint32_t m_szUnitLabel = 0xba0; // CUtlString
		constexpr uint32_t m_nUnitLabelIndex = 0xba8; // uint8
		constexpr uint32_t m_strAnimationModifier = 0xbb0; // CUtlString
		constexpr uint32_t m_TerrainSpecificFootstepEffect = 0xbb8; // CUtlString
		constexpr uint32_t m_bUseCustomTerrainWeatherEffect = 0xbc0; // bool
		constexpr uint32_t m_bHasClientSoundReplacement = 0xbc1; // bool
		constexpr uint32_t m_bHasClientReplacementParticle = 0xbc2; // bool
		constexpr uint32_t m_bResourcesLoaded = 0xbcc; // bool
		constexpr uint32_t m_flTauntCooldown = 0xbd0; // GameTime_t
		constexpr uint32_t m_flTauntCooldown2 = 0xbd4; // GameTime_t
		constexpr uint32_t m_iCurShop = 0xbd8; // DOTA_SHOP_TYPE
		constexpr uint32_t m_szCurShopEntName = 0xbe0; // CUtlSymbolLarge
		constexpr uint32_t m_iDayTimeVisionRange = 0xbe8; // int32
		constexpr uint32_t m_iNightTimeVisionRange = 0xbec; // int32
		constexpr uint32_t m_iDamageMin = 0xbf0; // int32
		constexpr uint32_t m_iDamageMax = 0xbf4; // int32
		constexpr uint32_t m_iDamageBonus = 0xbf8; // int32
		constexpr uint32_t m_iTaggedAsVisibleByTeam = 0xbfc; // int32
		constexpr uint32_t m_ModifierManager = 0xc00; // CDOTA_ModifierManager
		constexpr uint32_t m_Inventory = 0xe60; // C_DOTA_UnitInventory
		constexpr uint32_t m_nUnitState64 = 0xf18; // uint64
		constexpr uint32_t m_nUnitDebuffState = 0xf28; // uint64
		constexpr uint32_t m_bHasInventory = 0xf30; // bool
		constexpr uint32_t m_iAcquisitionRange = 0xf34; // int32
		constexpr uint32_t m_FoWViewID = 0xf38; // int32
		constexpr uint32_t m_iPrevHealthPct = 0xf3c; // int32
		constexpr uint32_t m_iPrevLifeState = 0xf40; // int32
		constexpr uint32_t m_iPrevTeam = 0xf44; // int32
		constexpr uint32_t m_bPrevProvidesVision = 0xf48; // bool
		constexpr uint32_t m_nPrevControllableMask = 0xf50; // uint64
		constexpr uint32_t m_TagTime = 0xf60; // CountdownTimer
		constexpr uint32_t m_ClickedTime = 0xf78; // CountdownTimer
		constexpr uint32_t m_flIdleRunPoseStartTime = 0xf90; // GameTime_t[2]
		constexpr uint32_t m_flIdleRunPoseDuration = 0xf98; // float32[2]
		constexpr uint32_t m_bAnimationTransitionActive = 0xfa0; // bool
		constexpr uint32_t m_nAnimationTransitionPoseParameters = 0xfa4; // int32[2]
		constexpr uint32_t m_nAnimationTransitionInjuredPoseParameters = 0xfac; // int32[2]
		constexpr uint32_t m_nAnimationTransitionAggressivePoseParameters = 0xfb4; // int32[2]
		constexpr uint32_t m_flTimeSinceLastAbilityNag = 0x1018; // GameTime_t
		constexpr uint32_t m_iAttackCapabilities = 0x101c; // int32
		constexpr uint32_t m_iSpecialAbility = 0x1020; // int32
		constexpr uint32_t m_iMoveCapabilities = 0x1024; // int32
		constexpr uint32_t m_nPlayerOwnerID = 0x1028; // PlayerID_t
		constexpr uint32_t m_iszMinimapIcon = 0x1030; // CUtlSymbolLarge
		constexpr uint32_t m_flMinimapIconSize = 0x1040; // float32
		constexpr uint32_t m_bMinimapDisableTint = 0x1044; // bool
		constexpr uint32_t m_bMinimapDisableRotation = 0x1045; // bool
		constexpr uint32_t m_colorHeroGlow = 0x1046; // Color
		constexpr uint32_t m_iNearShopMask = 0x104c; // int32
		constexpr uint32_t m_nPoseParameterTurn = 0x1050; // int32
		constexpr uint32_t m_nPoseParameterRun = 0x1054; // int32
		constexpr uint32_t m_flLean = 0x1058; // float32
		constexpr uint32_t m_flRun = 0x105c; // float32
		constexpr uint32_t m_anglediff = 0x1060; // int32
		constexpr uint32_t m_bInfoKeyActive = 0x1064; // bool
		constexpr uint32_t m_bNewUpdateAssetModifiersNetworked = 0x1065; // bool
		constexpr uint32_t m_nAssetModifiersLastUpdatedTick = 0x1068; // GameTick_t
		constexpr uint32_t m_bSuppressGlow = 0x106c; // bool
		constexpr uint32_t m_bWasSinking = 0x106d; // bool
		constexpr uint32_t m_flRangeDisplayDist = 0x1070; // float32
		constexpr uint32_t m_szDefaultIdle = 0x11f0; // CUtlSymbolLarge
		constexpr uint32_t m_szDefaultRareIdle = 0x11f8; // CUtlSymbolLarge
		constexpr uint32_t m_damagetimer = 0x1200; // CountdownTimer
		constexpr uint32_t m_vRenderOrigin = 0x1218; // Vector
		constexpr uint32_t m_fZDelta = 0x1224; // float32
		constexpr uint32_t m_flDeathTime = 0x1228; // GameTime_t
		constexpr uint32_t m_bBaseStatsChanged = 0x122c; // bool
		constexpr uint32_t m_bNeedsSoundEmitterRefresh = 0x122d; // bool
		constexpr uint32_t m_flPhysicalArmorValue = 0x1230; // float32
		constexpr uint32_t m_flMagicalResistanceValue = 0x1234; // float32
		constexpr uint32_t m_nPrevSequenceParity = 0x1238; // int32
		constexpr uint32_t m_flPrevInvisLevel = 0x12e0; // float32
		constexpr uint32_t m_nOriginalModelIndex = 0x12e8; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_nClientOriginalModelIndex = 0x12f0; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_nClientReplacementModelIndex = 0x12f8; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_bClientReplacementModelNeedsRebuild = 0x1300; // bool
		constexpr uint32_t m_nClientReplacementModelReloadCount = 0x1304; // int32
		constexpr uint32_t m_nUnitModelVariant = 0x1308; // int8
		constexpr uint32_t m_nUnitModelVariantCount = 0x1309; // int8
		constexpr uint32_t m_iPrevSequence = 0x130c; // int32
		constexpr uint32_t m_pLastWeatherEffectName = 0x1310; // char*
		constexpr uint32_t m_VoiceBackgroundSoundTimer = 0x1320; // CountdownTimer
		constexpr uint32_t m_bIsWaitingToSpawn = 0x1338; // bool
		constexpr uint32_t m_nTotalDamageTaken = 0x1340; // int64
		constexpr uint32_t m_flManaRegen = 0x1348; // float32
		constexpr uint32_t m_flHealthRegen = 0x134c; // float32
		constexpr uint32_t m_bIsMoving = 0x1350; // bool
		constexpr uint32_t m_fRevealRadius = 0x1354; // float32
		constexpr uint32_t m_bCanUseWards = 0x1358; // bool
		constexpr uint32_t m_bCanUseAllItems = 0x1359; // bool
		constexpr uint32_t m_iXPBounty = 0x135c; // int32
		constexpr uint32_t m_iXPBountyExtra = 0x1360; // int32
		constexpr uint32_t m_iGoldBountyMin = 0x1364; // int32
		constexpr uint32_t m_iGoldBountyMax = 0x1368; // int32
		constexpr uint32_t m_hGoalEntity = 0x136c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hNeutralSpawner = 0x1370; // CHandle< C_DOTA_NeutralSpawner >
		constexpr uint32_t m_hClientOverrideMaterial = 0x1378; // CStrongHandle< InfoForResourceTypeIMaterial2 >
		constexpr uint32_t m_bCombinerMaterialOverrideListChanged = 0x1380; // bool
		constexpr uint32_t m_nBaseModelMeshCount = 0x1384; // int32
		constexpr uint32_t m_combinerMaterialOverrideList = 0x1388; // CUtlVector< CStrongHandleCopyable< InfoForResourceTypeIMaterial2 > >
		constexpr uint32_t m_nArcanaLevel = 0x13a0; // int8
		constexpr uint32_t m_nDefaultArcanaLevel = 0x13a1; // int8
		constexpr uint32_t m_defaultColorGemColor = 0x13a2; // Color
		constexpr uint32_t m_bHasBuiltWearableSpawnList = 0x13c0; // bool
		constexpr uint32_t m_bHasCostume = 0x13c1; // bool
		constexpr uint32_t m_NetworkActivity = 0x14e0; // int32
		constexpr uint32_t m_PrevNetworkActivity = 0x14e4; // int32
		constexpr uint32_t m_NetworkSequenceIndex = 0x14e8; // int32
		constexpr uint32_t m_bShouldDoFlyHeightVisual = 0x14ec; // bool
		constexpr uint32_t m_flStartSequenceCycle = 0x14f0; // float32
		constexpr uint32_t m_ActivityModifiers = 0x14f8; // CUtlVector< CUtlSymbol >
		constexpr uint32_t m_hBackgroundSceneEnt = 0x1510; // CHandle< C_SceneEntity >
		constexpr uint32_t m_hSpeakingSceneEnt = 0x1514; // CHandle< C_SceneEntity >
		constexpr uint32_t m_hOldWearables = 0x1528; // CUtlVector< CHandle< C_EconWearable > >
		constexpr uint32_t m_hOldWearableSkins = 0x1540; // CUtlVector< CUtlStringToken >
		constexpr uint32_t m_CustomHealthLabel = 0x1558; // char[256]
		constexpr uint32_t m_CustomHealthLabelColor = 0x1658; // Color
		constexpr uint32_t m_nWearableDefIndex = 0x165c; // item_definition_index_t
		constexpr uint32_t m_gibTintColor = 0x1661; // Color
		constexpr uint32_t m_bForceMaterialCombine = 0x1665; // bool
		constexpr uint32_t m_bShouldDrawParticlesWhileHidden = 0x1666; // bool
		constexpr uint32_t m_bIsClientThinkPending = 0x1667; // bool
		constexpr uint32_t m_bActivityModifiersDirty = 0x1668; // bool
		constexpr uint32_t m_bUnitModelVariantChanged = 0x1669; // bool
		constexpr uint32_t m_bWearablesAreTaunting = 0x166a; // bool
		constexpr uint32_t m_bShowCannotBeDisabledIcon = 0x1680; // bool
	}
	namespace CBasePlayerController {
		constexpr uint32_t m_nFinalPredictedTick = 0x530; // int32
		constexpr uint32_t m_CommandContext = 0x538; // C_CommandContext
		constexpr uint32_t m_nInButtonsWhichAreToggles = 0x5b0; // uint64
		constexpr uint32_t m_nTickBase = 0x5b8; // uint32
		constexpr uint32_t m_hPawn = 0x5bc; // CHandle< C_BasePlayerPawn >
		constexpr uint32_t m_hPredictedPawn = 0x5c0; // CHandle< C_BasePlayerPawn >
		constexpr uint32_t m_nSplitScreenSlot = 0x5c4; // CSplitScreenSlot
		constexpr uint32_t m_hSplitOwner = 0x5c8; // CHandle< CBasePlayerController >
		constexpr uint32_t m_hSplitScreenPlayers = 0x5d0; // CUtlVector< CHandle< CBasePlayerController > >
		constexpr uint32_t m_bIsHLTV = 0x5e8; // bool
		constexpr uint32_t m_iConnected = 0x5ec; // PlayerConnectedState
		constexpr uint32_t m_iszPlayerName = 0x5f0; // char[128]
		constexpr uint32_t m_steamID = 0x678; // uint64
		constexpr uint32_t m_bIsLocalPlayerController = 0x680; // bool
		constexpr uint32_t m_iDesiredFOV = 0x684; // uint32
	}
	namespace CEntityInstance {
		constexpr uint32_t m_iszPrivateVScripts = 0x8; // CUtlSymbolLarge
		constexpr uint32_t m_pEntity = 0x10; // CEntityIdentity*
		constexpr uint32_t m_CScriptComponent = 0x28; // CScriptComponent*
	}
	namespace C_DOTA_BaseNPC_Hero {
		constexpr uint32_t m_bBuybackDisabled = 0x0; // bitfield:1
		constexpr uint32_t m_iCurrentXP = 0x1690; // int32
		constexpr uint32_t m_iAbilityPoints = 0x1694; // int32
		constexpr uint32_t m_flRespawnTime = 0x1698; // GameTime_t
		constexpr uint32_t m_flRespawnTimePenalty = 0x169c; // float32
		constexpr uint32_t m_flStrength = 0x16a0; // float32
		constexpr uint32_t m_flAgility = 0x16a4; // float32
		constexpr uint32_t m_flIntellect = 0x16a8; // float32
		constexpr uint32_t m_flStrengthTotal = 0x16ac; // float32
		constexpr uint32_t m_flAgilityTotal = 0x16b0; // float32
		constexpr uint32_t m_flIntellectTotal = 0x16b4; // float32
		constexpr uint32_t m_flDeathTime = 0x16b8; // GameTime_t
		constexpr uint32_t m_iRecentDamage = 0x16bc; // int32
		constexpr uint32_t m_fPainFactor = 0x16c0; // float32
		constexpr uint32_t m_fTargetPainFactor = 0x16c4; // float32
		constexpr uint32_t m_bLifeState = 0x16c8; // bool
		constexpr uint32_t m_nFXStunIndex = 0x16cc; // ParticleIndex_t
		constexpr uint32_t m_nFXSilenceIndex = 0x16d0; // ParticleIndex_t
		constexpr uint32_t m_nFXDeathIndex = 0x16d4; // ParticleIndex_t
		constexpr uint32_t m_iPlayerID = 0x16f8; // PlayerID_t
		constexpr uint32_t m_hReplicatingOtherHeroModel = 0x16fc; // CHandle< C_DOTA_BaseNPC_Hero >
		constexpr uint32_t m_bReincarnating = 0x1700; // bool
		constexpr uint32_t m_bCustomKillEffect = 0x1701; // bool
		constexpr uint32_t m_flSpawnedAt = 0x1704; // GameTime_t
		constexpr uint32_t m_bScriptDisableRespawns = 0x1708; // bool
		constexpr uint32_t m_iPrimaryAttribute = 0x170c; // int32
		constexpr uint32_t m_nLastDrawnHealth = 0x1710; // int32
		constexpr uint32_t m_flHurtAmount = 0x1714; // float32
		constexpr uint32_t m_flLastHurtTime = 0x1718; // GameTime_t
		constexpr uint32_t m_flHurtDecayRate = 0x171c; // float32
		constexpr uint32_t m_flLastHealTime = 0x1720; // GameTime_t
		constexpr uint32_t m_flLastTreeShakeTime = 0x1724; // GameTime_t
		constexpr uint32_t m_CenterOnHeroCooldownTimer = 0x1728; // CountdownTimer
		constexpr uint32_t m_CombinedModels = 0x1948; // CStrongHandle< InfoForResourceTypeCModel >[4]
		constexpr uint32_t m_nCurrentCombinedModelIndex = 0x1968; // int32
		constexpr uint32_t m_nPendingCombinedModelIndex = 0x196c; // int32
		constexpr uint32_t m_iHeroID = 0x1970; // int32
		constexpr uint32_t m_flCheckLegacyItemsAt = 0x1974; // float32
		constexpr uint32_t m_bDisplayAdditionalHeroes = 0x1978; // bool
		constexpr uint32_t m_CombinedParticleModels = 0x1988; // CStrongHandle< InfoForResourceTypeCModel >[4]
		constexpr uint32_t m_vecAttachedParticleIndeces = 0x19a8; // CUtlVector< ParticleIndex_t >
		constexpr uint32_t m_hPets = 0x19c0; // CUtlVector< CHandle< C_BaseEntity > >
		constexpr uint32_t m_nKillStreakFX = 0x19d8; // ParticleIndex_t
		constexpr uint32_t m_nKillStreakFXTier = 0x19dc; // int32
	}
	namespace C_BaseFlex {
		constexpr uint32_t m_flexWeight = 0x7d8; // C_NetworkUtlVectorBase< float32 >
		constexpr uint32_t m_blinktoggle = 0x7f0; // bool
		constexpr uint32_t m_vLookTargetPosition = 0x7f8; // Vector
		constexpr uint32_t m_nLastFlexUpdateFrameCount = 0x868; // int32
		constexpr uint32_t m_CachedViewTarget = 0x86c; // Vector
		constexpr uint32_t m_nNextSceneEventId = 0x880; // uint32
		constexpr uint32_t m_iBlink = 0x884; // int32
		constexpr uint32_t m_blinktime = 0x888; // float32
		constexpr uint32_t m_prevblinktoggle = 0x88c; // bool
		constexpr uint32_t m_iMouthAttachment = 0x88d; // AttachmentHandle_t
		constexpr uint32_t m_iEyeAttachment = 0x88e; // AttachmentHandle_t
		constexpr uint32_t m_bResetFlexWeightsOnModelChange = 0x88f; // bool
		constexpr uint32_t m_nEyeOcclusionRendererBone = 0x8a8; // int32
		constexpr uint32_t m_mEyeOcclusionRendererCameraToBoneTransform = 0x8ac; // matrix3x4_t
		constexpr uint32_t m_vEyeOcclusionRendererHalfExtent = 0x8dc; // Vector
		constexpr uint32_t m_PhonemeClasses = 0x8f8; // C_BaseFlex::Emphasized_Phoneme[3]
	}
	namespace CBaseAnimatingActivity {
		constexpr uint32_t m_bShouldAnimateDuringGameplayPause = 0x7a8; // bool
		constexpr uint32_t m_bInitiallyPopulateInterpHistory = 0x7a9; // bool
		constexpr uint32_t m_pSuppressedAnimEventTags = 0x7b0; // CUtlVector< CUtlString >*
		constexpr uint32_t m_bHasAnimatedMaterialAttributes = 0x7b8; // bool
		constexpr uint32_t m_bSuppressAnimEventSounds = 0x7c8; // bool
	}
	namespace C_DOTA_UnitInventory {
		constexpr uint32_t m_SharedCooldownList = 0x8; // CUtlVector< sSharedCooldownInfo >
		constexpr uint32_t m_hItems = 0x20; // CHandle< C_BaseEntity >[19]
		constexpr uint32_t m_bItemQueried = 0x6c; // bool[19]
		constexpr uint32_t m_iParity = 0x80; // int32
		constexpr uint32_t m_hInventoryParent = 0x84; // CHandle< C_BaseEntity >
		constexpr uint32_t m_bIsActive = 0x88; // bool
		constexpr uint32_t m_bStashEnabled = 0x89; // bool
		constexpr uint32_t m_hTransientCastItem = 0x8c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_bSendChangedMsg = 0xa8; // bool
	}
	namespace C_BaseModelEntity {
		constexpr uint32_t m_CRenderComponent = 0x528; // CRenderComponent*
		constexpr uint32_t m_CHitboxComponent = 0x530; // CHitboxComponent
		constexpr uint32_t m_bInitModelEffects = 0x578; // bool
		constexpr uint32_t m_bIsStaticProp = 0x579; // bool
		constexpr uint32_t m_iViewerID = 0x57c; // int32
		constexpr uint32_t m_iTeamVisibilityBitmask = 0x580; // int32
		constexpr uint32_t m_nLastAddDecal = 0x584; // int32
		constexpr uint32_t m_nDecalsAdded = 0x588; // int32
		constexpr uint32_t m_iOldHealth = 0x58c; // int32
		constexpr uint32_t m_nRenderMode = 0x590; // RenderMode_t
		constexpr uint32_t m_bVisibilityDirtyFlag = 0x591; // bool
		constexpr uint32_t m_nRenderFX = 0x592; // RenderFx_t
		constexpr uint32_t m_bAllowFadeInView = 0x593; // bool
		constexpr uint32_t m_clrRender = 0x594; // Color
		constexpr uint32_t m_vecRenderAttributes = 0x598; // C_UtlVectorEmbeddedNetworkVar< EntityRenderAttribute_t >
		constexpr uint32_t m_LightGroup = 0x600; // CUtlStringToken
		constexpr uint32_t m_bRenderToCubemaps = 0x604; // bool
		constexpr uint32_t m_Collision = 0x608; // CCollisionProperty
		constexpr uint32_t m_Glow = 0x6b8; // CGlowProperty
		constexpr uint32_t m_flGlowBackfaceMult = 0x710; // float32
		constexpr uint32_t m_fadeMinDist = 0x714; // float32
		constexpr uint32_t m_fadeMaxDist = 0x718; // float32
		constexpr uint32_t m_flFadeScale = 0x71c; // float32
		constexpr uint32_t m_flShadowStrength = 0x720; // float32
		constexpr uint32_t m_nObjectCulling = 0x724; // uint8
		constexpr uint32_t m_nAddDecal = 0x728; // int32
		constexpr uint32_t m_vDecalPosition = 0x72c; // Vector
		constexpr uint32_t m_vDecalForwardAxis = 0x738; // Vector
		constexpr uint32_t m_flDecalHealBloodRate = 0x744; // float32
		constexpr uint32_t m_flDecalHealHeightRate = 0x748; // float32
		constexpr uint32_t m_ConfigEntitiesToPropagateMaterialDecalsTo = 0x750; // C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > >
		constexpr uint32_t m_vecViewOffset = 0x768; // CNetworkViewOffsetVector
		constexpr uint32_t m_pClientAlphaProperty = 0x798; // CClientAlphaProperty*
		constexpr uint32_t m_ClientOverrideTint = 0x7a0; // Color
		constexpr uint32_t m_bUseClientOverrideTint = 0x7a4; // bool
	}
	namespace C_DOTAPlayerController {
		constexpr uint32_t m_iMinimapMove = 0x728; // int32
		constexpr uint32_t m_pClickBehaviorKeys = 0x730; // KeyValues*
		constexpr uint32_t m_flCenterTime = 0x738; // GameTime_t
		constexpr uint32_t m_iConfirmationIndex = 0x73c; // int32
		constexpr uint32_t m_bCenterOnHero = 0x740; // bool
		constexpr uint32_t m_bHeroAssigned = 0x741; // bool
		constexpr uint32_t m_nKeyBindHeroID = 0x744; // int32
		constexpr uint32_t m_bUsingCameraMan = 0x748; // bool
		constexpr uint32_t m_bUsingAssistedCameraOperator = 0x749; // bool
		constexpr uint32_t m_nPlayerAssistFlags = 0x74c; // int32
		constexpr uint32_t m_vLatestEvent = 0x750; // Vector
		constexpr uint32_t m_hFreeDrawAbility = 0x780; // CHandle< C_DOTABaseAbility >
		constexpr uint32_t m_vLastFreeDrawPosition = 0x784; // Vector
		constexpr uint32_t m_nPlayerID = 0x790; // PlayerID_t
		constexpr uint32_t m_hAssignedHero = 0x794; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hLastAssignedHero = 0x798; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hKillCamUnit = 0x79c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hPreviousKillCamUnit = 0x7a0; // CHandle< C_BaseEntity >
		constexpr uint32_t m_flKillCamUnitReceivedTime = 0x7a4; // float32
		constexpr uint32_t m_nRareLineClickCount = 0x7b0; // int32
		constexpr uint32_t m_nRareLinesPlayed = 0x7b4; // int32
		constexpr uint32_t m_nRareLineGroup = 0x7b8; // int32
		constexpr uint32_t m_flLastRareLinePlayTime = 0x7bc; // float32
		constexpr uint32_t m_flNextUnitOrdersTime = 0x7c0; // float32
		constexpr uint32_t m_bTeleportRequiresHalt = 0x7c4; // bool
		constexpr uint32_t m_bChannelRequiresHalt = 0x7c5; // bool
		constexpr uint32_t m_bAutoPurchaseItems = 0x7c6; // bool
		constexpr uint32_t m_bDisableHUDErrorMessages = 0x7c7; // bool
		constexpr uint32_t m_iMouseDragStartX = 0x7c8; // int32
		constexpr uint32_t m_iMouseDragStartY = 0x7cc; // int32
		constexpr uint32_t m_nWeatherType = 0x7d0; // int32
		constexpr uint32_t m_bDynamicWeatherSystemActive = 0x7d4; // bool
		constexpr uint32_t m_bDynamicSoundHandled = 0x7d5; // bool
		constexpr uint32_t m_flDynamicWeatherNextSwitchTime = 0x7d8; // GameTime_t
		constexpr uint32_t m_flDynamicWeatherScaleFinishedTime = 0x7dc; // GameTime_t
		constexpr uint32_t m_flDynamicWeatherIntensity = 0x7e0; // float32
		constexpr uint32_t m_nXPRangeFXIndex = 0x7e4; // ParticleIndex_t
		constexpr uint32_t m_nVisionRangeFXIndex = 0x7e8; // ParticleIndex_t
		constexpr uint32_t m_nSelectedControlGroup = 0x7ec; // int32
		constexpr uint32_t m_nCachedCoachedTeam = 0x7f0; // int32
		constexpr uint32_t m_hActiveAbility = 0x7f4; // CHandle< C_DOTABaseAbility >
		constexpr uint32_t m_unitorders = 0x7f8; // CUtlVector< CUnitOrders >
		constexpr uint32_t m_nOutgoingOrderSequenceNumber = 0x810; // int32
		constexpr uint32_t m_nServerOrderSequenceNumber = 0x814; // int32
		constexpr uint32_t m_nSelectedUnits = 0x818; // CUtlVector< CEntityIndex >
		constexpr uint32_t m_nWaypoints = 0x830; // CUtlVector< ParticleIndex_t >
		constexpr uint32_t m_iActions = 0x848; // int32
		constexpr uint32_t m_hQueryUnit = 0x84c; // CHandle< C_DOTA_BaseNPC >
		constexpr uint32_t m_bInQuery = 0x850; // bool
		constexpr uint32_t m_bSelectionChangedInDataUpdate = 0x851; // bool
		constexpr uint32_t m_flQueryInhibitingActionTime = 0x8b8; // GameTime_t
		constexpr uint32_t m_flQueryInhibitDuration = 0x8bc; // float32
		constexpr uint32_t m_RingedEntities = 0x8c0; // CUtlVector< CHandle< C_BaseEntity > >
		constexpr uint32_t m_ActiveRingOwners = 0x8d8; // CUtlVector< CHandle< C_BaseEntity > >
		constexpr uint32_t m_bOverridingQuery = 0x8f0; // bool
		constexpr uint32_t m_flLastAutoRepeatTime = 0x8f8; // float32
		constexpr uint32_t m_flConsumeDoubleclickTime = 0x8fc; // float32
		constexpr uint32_t m_LightInfoWeatherEffect = 0x900; // CUtlString
		constexpr uint32_t m_bPreviousWasLightInfoWeather = 0x908; // bool
		constexpr uint32_t m_MapDefaultWeatherEffect = 0x910; // CUtlString
		constexpr uint32_t m_bMapUsesDynamicWeather = 0x918; // bool
		constexpr uint32_t m_vecSuggestedWardLocationEffects = 0x958; // CUtlVector< ParticleIndex_t >
		constexpr uint32_t m_pSmartCastNPC = 0x970; // C_DOTA_BaseNPC*
		constexpr uint32_t m_nTeamSprayParticleIndex = 0x978; // ParticleIndex_t
		constexpr uint32_t m_bIsNextCastOrderFromMouseClick = 0x97c; // bool
		constexpr uint32_t m_iCursor = 0x9b0; // int32[2]
		constexpr uint32_t m_iSpectatorClickBehavior = 0x9b8; // int32
		constexpr uint32_t m_flAspectRatio = 0x9bc; // float32
		constexpr uint32_t m_hSpectatorQueryUnit = 0x9c0; // CHandle< C_BaseEntity >
		constexpr uint32_t m_iStatsPanel = 0x9c4; // int32
		constexpr uint32_t m_iShopPanel = 0x9c8; // int32
		constexpr uint32_t m_iShopViewMode = 0x9cc; // ShopItemViewMode_t
		constexpr uint32_t m_iStatsDropdownCategory = 0x9d0; // int32
		constexpr uint32_t m_iStatsDropdownSort = 0x9d4; // int32
		constexpr uint32_t m_szShopString = 0x9d8; // char[64]
		constexpr uint32_t m_vecClientQuickBuyState = 0xa18; // C_UtlVectorEmbeddedNetworkVar< ClientQuickBuyItemState >
		constexpr uint32_t m_bInShowCaseMode = 0xa68; // bool
		constexpr uint32_t m_flCameraZoomAmount = 0xa6c; // float32
		constexpr uint32_t m_iHighPriorityScore = 0xa70; // int32
		constexpr uint32_t m_quickBuyItems = 0xa74; // AbilityID_t[9]
		constexpr uint32_t m_quickBuyIsPurchasable = 0xa98; // bool[9]
		constexpr uint32_t m_flFrameTime = 0xaa4; // float32
		constexpr uint32_t m_flFrameTimeStdDev = 0xaa8; // float32
		constexpr uint32_t m_flUnfilteredFrameTime = 0xaac; // float32
		constexpr uint32_t m_NeutralCampAlarms = 0xab0; // CUtlVector< NeutralCampStackPullAlarm_t >
		constexpr uint32_t m_iPrevCursor = 0xac8; // int32[2]
		constexpr uint32_t m_iPositionHistoryTail = 0xb70; // int32
		constexpr uint32_t m_iMusicStatus = 0xb74; // int32
		constexpr uint32_t m_iPreviousMusicStatus = 0xb78; // int32
		constexpr uint32_t m_bRequestedInventory = 0xb7c; // bool
		constexpr uint32_t m_flMusicOperatorVals = 0xb80; // float32[3]
		constexpr uint32_t m_iMusicOperatorVals = 0xb8c; // int32[4]
		constexpr uint32_t m_ControlGroups = 0xba0; // CUtlVector< sControlGroupElem >[10]
		constexpr uint32_t m_pkvControlGroupKV = 0xc90; // KeyValues*
		constexpr uint32_t m_flAltHeldStartTime = 0xcf0; // float32
	}
	namespace CDOTA_Buff {
		constexpr uint32_t m_bIsAura = 0x0; // bitfield:1
		constexpr uint32_t m_name = 0x28; // CUtlSymbolLarge
		constexpr uint32_t m_szModifierAura = 0x38; // CUtlSymbolLarge
		constexpr uint32_t m_iSerialNumber = 0x48; // int32
		constexpr uint32_t m_iStringIndex = 0x4c; // int32
		constexpr uint32_t m_iIndex = 0x50; // int32
		constexpr uint32_t m_flCreationTime = 0x54; // GameTime_t
		constexpr uint32_t m_iCreationFrame = 0x58; // int32
		constexpr uint32_t m_flLastAppliedTime = 0x5c; // GameTime_t
		constexpr uint32_t m_flDuration = 0x60; // float32
		constexpr uint32_t m_flDieTime = 0x64; // GameTime_t
		constexpr uint32_t m_hCaster = 0x68; // CHandle< CBaseEntity >
		constexpr uint32_t m_hAbility = 0x6c; // CHandle< CBaseEntity >
		constexpr uint32_t m_hParent = 0x70; // CHandle< CBaseEntity >
		constexpr uint32_t m_hAuraOwner = 0x74; // CHandle< CBaseEntity >
		constexpr uint32_t m_iStackCount = 0x78; // int32
		constexpr uint32_t m_iAuraSearchTeam = 0x7c; // int16
		constexpr uint32_t m_iAuraSearchType = 0x7e; // int16
		constexpr uint32_t m_iAuraSearchFlags = 0x80; // int32
		constexpr uint32_t m_iAuraRadius = 0x84; // int32
		constexpr uint32_t m_iTeam = 0x88; // int32
		constexpr uint32_t m_iAttributes = 0x8c; // int32
		constexpr uint32_t m_iPaddingToMakeSchemaHappy2 = 0x90; // int16
		constexpr uint32_t m_bPurgedDestroy = 0x93; // bool
		constexpr uint32_t m_flPreviousTick = 0x94; // GameTime_t
		constexpr uint32_t m_flThinkInterval = 0x98; // float32
		constexpr uint32_t m_flThinkTimeAccumulator = 0x9c; // float32
		constexpr uint32_t m_iParticles = 0xa0; // CUtlVector< CDOTA_BuffParticle >
		constexpr uint32_t m_hAuraUnits = 0xb8; // CUtlVector< CHandle< CBaseEntity > >
		constexpr uint32_t m_hScriptScope = 0x1130; // HSCRIPT
	}
	namespace C_DOTA_PlayerResource {
		constexpr uint32_t m_bWasDataUpdateCreated = 0x538; // bool
		constexpr uint32_t m_vecPlayerTeamData = 0x540; // C_UtlVectorEmbeddedNetworkVar< PlayerResourcePlayerTeamData_t >
		constexpr uint32_t m_vecPlayerData = 0x590; // C_UtlVectorEmbeddedNetworkVar< PlayerResourcePlayerData_t >
		constexpr uint32_t m_vecBrodcasterData = 0x5e0; // C_UtlVectorEmbeddedNetworkVar< PlayerResourceBroadcasterData_t >
		constexpr uint32_t m_vecEventsForDisplay = 0x630; // C_NetworkUtlVectorBase< uint32 >
		constexpr uint32_t m_nPrimaryEventIndex = 0x648; // int8
		constexpr uint32_t m_nObsoleteEventIDAssociatedWithEventData = 0x64c; // uint32
		constexpr uint32_t m_playerIDToPlayer = 0x650; // CHandle< C_BaseEntity >[64]
		constexpr uint32_t m_iszName = 0x750; // CUtlSymbolLarge[64]
		constexpr uint32_t m_iszHTMLSafeName = 0x950; // CUtlSymbolLarge[64]
		constexpr uint32_t m_iszFilteredHTMLSafeName = 0xb50; // CUtlSymbolLarge[64]
		constexpr uint32_t m_bDirtySuggestedItems = 0x2550; // bool
		constexpr uint32_t m_bDirtyEstimatedMatchDuration = 0x2551; // bool
		constexpr uint32_t m_bDirtySelection = 0x2552; // bool
		constexpr uint32_t m_bHasWorldTreesChanged = 0x2553; // bool
		constexpr uint32_t m_bWorldTreeModelsChanged = 0x2554; // bool
		constexpr uint32_t m_bSwapWillingness = 0x2555; // bool[24]
		constexpr uint32_t m_hTeamCouriers = 0x2570; // CUtlVector< CHandle< C_DOTA_Unit_Courier > >[14]
		constexpr uint32_t m_hPlayerCouriers = 0x26c0; // CUtlVector< CHandle< C_DOTA_Unit_Courier > >[64]
		constexpr uint32_t m_vecOnstageHomeTeams = 0x2cc0; // CUtlVector< uint32 >
		constexpr uint32_t m_pPlayerIDToOnstageSlot = 0x2cd8; // PlayerSeatAssignment_t*[24]
		constexpr uint32_t m_vecOnstagePlayerSeats = 0x2d98; // CUtlVector< PlayerSeatAssignment_t >
		constexpr uint32_t m_nEventNPCReplaced = 0x2db0; // int32
		constexpr uint32_t m_nEventPlayerInfo = 0x2db4; // int32
		constexpr uint32_t m_nInventoryUpdated = 0x2db8; // int32
	}
	namespace C_DOTAGamerules {
		constexpr uint32_t __m_pChainEntity = 0x8; // CNetworkVarChainer
		constexpr uint32_t m_nTotalPausedTicks = 0x30; // int32
		constexpr uint32_t m_nPauseStartTick = 0x34; // int32
		constexpr uint32_t m_bGamePaused = 0x38; // bool
		constexpr uint32_t m_bGameTimeFrozen = 0x39; // bool
		constexpr uint32_t m_iMiscHeroPickCounter = 0x3c; // int32
		constexpr uint32_t m_hEndGameCinematicEntity = 0x40; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hOverlayHealthBarUnit = 0x44; // CHandle< C_DOTA_BaseNPC >
		constexpr uint32_t m_nOverlayHealthBarType = 0x48; // int32
		constexpr uint32_t m_bIsInCinematicMode = 0x4c; // bool
		constexpr uint32_t m_bIsInClientSideCinematicMode = 0x4d; // bool
		constexpr uint32_t m_bFreeCourierMode = 0x4e; // bool
		constexpr uint32_t m_nStartingGold = 0x50; // int32
		constexpr uint32_t m_nGoldPerTick = 0x54; // int32
		constexpr uint32_t m_flGoldTickTime = 0x58; // float32
		constexpr uint32_t m_bItemWhiteListChanged = 0x5c; // bool
		constexpr uint32_t m_bEnableSuggestAbilities = 0x5d; // bool
		constexpr uint32_t m_bEnableSuggestItems = 0x5e; // bool
		constexpr uint32_t m_unFanfareGoodGuys = 0x60; // uint32
		constexpr uint32_t m_unFanfareBadGuys = 0x64; // uint32
		constexpr uint32_t m_iMapType = 0x68; // int32
		constexpr uint32_t m_nServerGameState = 0x6c; // int32
		constexpr uint32_t m_nServerHeroPickState = 0x70; // DOTA_HeroPickState
		constexpr uint32_t m_nGameState = 0x74; // int32
		constexpr uint32_t m_nHeroPickState = 0x78; // DOTA_HeroPickState
		constexpr uint32_t m_bAlternateHeroGridsEnabled = 0x7c; // bool
		constexpr uint32_t m_flStateTransitionTime = 0x80; // GameTime_t
		constexpr uint32_t m_flOverride_dota_hero_selection_time = 0x84; // float32
		constexpr uint32_t m_flOverride_dota_pregame_time = 0x88; // float32
		constexpr uint32_t m_flOverride_dota_postgame_time = 0x8c; // float32
		constexpr uint32_t m_flOverride_dota_strategy_time = 0x90; // float32
		constexpr uint32_t m_flOverride_dota_team_showcase_duration = 0x94; // float32
		constexpr uint32_t m_flOverride_dota_rune_spawn_time = 0x98; // float32
		constexpr uint32_t m_flShowcaseTime = 0x9c; // float32[14]
		constexpr uint32_t m_flNeutralInitialSpawnOffset = 0xd4; // float32
		constexpr uint32_t m_iGameMode = 0xd8; // int32
		constexpr uint32_t m_hGameModeEntity = 0xdc; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hCustomHeroPickRulesEntity = 0xe0; // CHandle< C_BaseEntity >
		constexpr uint32_t m_flHeroPickStateTransitionTime = 0xe4; // GameTime_t
		constexpr uint32_t m_iPlayerIDsInControl = 0xe8; // uint64
		constexpr uint32_t m_bSameHeroSelectionEnabled = 0xf0; // bool
		constexpr uint32_t m_bUseCustomHeroXPValue = 0xf1; // bool
		constexpr uint32_t m_bUseBaseGoldBountyOnHeroes = 0xf2; // bool
		constexpr uint32_t m_bUseUniversalShopMode = 0xf3; // bool
		constexpr uint32_t m_bHideKillMessageHeaders = 0xf4; // bool
		constexpr uint32_t m_flHeroMinimapIconScale = 0xf8; // float32
		constexpr uint32_t m_flCreepMinimapIconScale = 0xfc; // float32
		constexpr uint32_t m_bCreepSpawningEnabled = 0x100; // bool
		constexpr uint32_t m_flRuneMinimapIconScale = 0x104; // float32
		constexpr uint32_t m_CustomVictoryMessage = 0x108; // char[256]
		constexpr uint32_t m_flCustomGameEndDelay = 0x208; // float32
		constexpr uint32_t m_flCustomGameSetupAutoLaunchDelay = 0x20c; // float32
		constexpr uint32_t m_flCustomGameSetupTimeout = 0x210; // float32
		constexpr uint32_t m_flCustomVictoryMessageDuration = 0x214; // float32
		constexpr uint32_t m_flHeroSelectPenaltyTime = 0x218; // float32
		constexpr uint32_t m_bCustomGameSetupAutoLaunchEnabled = 0x21c; // bool
		constexpr uint32_t m_bCustomGameTeamSelectionLocked = 0x21d; // bool
		constexpr uint32_t m_bCustomGameEnablePickRules = 0x21e; // bool
		constexpr uint32_t m_bCustomGameAllowHeroPickMusic = 0x21f; // bool
		constexpr uint32_t m_bCustomGameAllowMusicAtGameStart = 0x220; // bool
		constexpr uint32_t m_bCustomGameAllowBattleMusic = 0x221; // bool
		constexpr uint32_t m_bCustomGameDisableIK = 0x222; // bool
		constexpr uint32_t m_bCustomGameAllowSecondaryAbilitiesOnOtherUnits = 0x223; // bool
		constexpr uint32_t m_iCMModePickBanOrder = 0x224; // int32
		constexpr uint32_t m_iCDModePickBanOrder = 0x228; // int32
		constexpr uint32_t m_nGGTeam = 0x22c; // int32
		constexpr uint32_t m_flGGEndsAtTime = 0x230; // GameTime_t
		constexpr uint32_t m_bGGCalled = 0x234; // bool
		constexpr uint32_t m_bWhiteListEnabled = 0x235; // bool
		constexpr uint32_t m_bItemWhiteList = 0x238; // uint64[4]
		constexpr uint32_t m_nLastHitUIMode = 0x258; // int32
		constexpr uint32_t m_bHUDTimerTutorialMode = 0x25c; // bool
		constexpr uint32_t m_HeroPickMiscTimer = 0x260; // CountdownTimer
		constexpr uint32_t m_ExtraTimeTimer = 0x278; // CountdownTimer
		constexpr uint32_t m_fExtraTimeRemaining = 0x290; // float32[2]
		constexpr uint32_t m_bHeroRespawnEnabled = 0x298; // bool
		constexpr uint32_t m_bIsRandomingEnabled = 0x299; // bool
		constexpr uint32_t m_iCaptainPlayerIDs = 0x29c; // PlayerID_t[2]
		constexpr uint32_t m_BannedHeroes = 0x2a4; // int32[24]
		constexpr uint32_t m_SelectedHeroes = 0x304; // int32[24]
		constexpr uint32_t m_iActiveTeam = 0x364; // int32
		constexpr uint32_t m_iStartingTeam = 0x368; // int32
		constexpr uint32_t m_iPenaltyLevelRadiant = 0x36c; // int32
		constexpr uint32_t m_iPenaltyLevelDire = 0x370; // int32
		constexpr uint32_t m_bIsLoadingScenario = 0x374; // bool
		constexpr uint32_t m_vecNewBannedHeroes = 0x378; // C_NetworkUtlVectorBase< int32 >
		constexpr uint32_t m_vecWhitelistedHeroes = 0x390; // C_NetworkUtlVectorBase< int32 >
		constexpr uint32_t m_vecBlacklistedHeroes = 0x3a8; // C_NetworkUtlVectorBase< int32 >
		constexpr uint32_t m_bHideBlacklistedHeroes = 0x3c0; // bool
		constexpr uint32_t m_nSeriesType = 0x3c4; // int32
		constexpr uint32_t m_nRadiantSeriesWins = 0x3c8; // int32
		constexpr uint32_t m_nDireSeriesWins = 0x3cc; // int32
		constexpr uint32_t m_vecAvailableHerosPerPlayerID = 0x3d0; // C_UtlVectorEmbeddedNetworkVar< CHeroesPerPlayer >
		constexpr uint32_t m_vecLockedHerosByPlayerID = 0x420; // C_UtlVectorEmbeddedNetworkVar< CHeroesPerPlayer >
		constexpr uint32_t m_vecDisabledRandomHerosByPlayerID = 0x470; // C_UtlVectorEmbeddedNetworkVar< CHeroesPerPlayer >
		constexpr uint32_t m_CustomGameForceSelectHero = 0x4c0; // int32[24]
		constexpr uint32_t m_flGoldTime = 0x520; // float32
		constexpr uint32_t m_flXPTime = 0x524; // float32
		constexpr uint32_t m_flCreepSpawntime = 0x528; // GameTime_t
		constexpr uint32_t m_flAnnounceStartTime = 0x52c; // float32
		constexpr uint32_t m_iGoodTomeCount = 0x530; // int32
		constexpr uint32_t m_iBadTomeCount = 0x534; // int32
		constexpr uint32_t m_flPreGameStartTime = 0x538; // GameTime_t
		constexpr uint32_t m_flGameStartTime = 0x53c; // GameTime_t
		constexpr uint32_t m_flGameEndTime = 0x540; // GameTime_t
		constexpr uint32_t m_flGameLoadTime = 0x544; // float32
		constexpr uint32_t m_iCustomGameScore = 0x548; // int32[2]
		constexpr uint32_t m_nCustomGameDifficulty = 0x550; // int32
		constexpr uint32_t m_bEnemyModifiersEnabled = 0x554; // bool
		constexpr uint32_t m_iWaves = 0x558; // int32
		constexpr uint32_t m_iCreepUpgradeState = 0x55c; // int32
		constexpr uint32_t m_fGoodGlyphCooldown = 0x560; // GameTime_t
		constexpr uint32_t m_fBadGlyphCooldown = 0x564; // GameTime_t
		constexpr uint32_t m_flGlyphCooldowns = 0x568; // GameTime_t[14]
		constexpr uint32_t m_fGoodRadarCooldown = 0x5a0; // GameTime_t
		constexpr uint32_t m_fBadRadarCooldown = 0x5a4; // GameTime_t
		constexpr uint32_t m_flRadarCooldowns = 0x5a8; // GameTime_t[14]
		constexpr uint32_t m_flOutpostTimes = 0x5e0; // float32[24]
		constexpr uint32_t m_bIsNightstalkerNight = 0x640; // bool
		constexpr uint32_t m_bIsTemporaryNight = 0x641; // bool
		constexpr uint32_t m_bIsTemporaryDay = 0x642; // bool
		constexpr uint32_t m_nRiverType = 0x644; // int32
		constexpr uint32_t m_nTeamFeaturedPlayerID = 0x648; // PlayerID_t[14]
		constexpr uint32_t m_nTeamVersusScreen = 0x680; // item_definition_index_t[14]
		constexpr uint32_t m_flGoldRedistributeTime = 0x6b8; // float32
		constexpr uint32_t m_nGoldToRedistribute = 0x6bc; // int32[2]
		constexpr uint32_t m_flNextPreGameThink = 0x6c4; // GameTime_t
		constexpr uint32_t m_flNextAllDraftGoldThink = 0x6c8; // GameTime_t
		constexpr uint32_t m_flTimeEnteredState = 0x6d0; // float64
		constexpr uint32_t m_unRiverAccountID = 0x6d8; // uint32
		constexpr uint32_t m_ulRiverItemID = 0x6e0; // itemid_t
		constexpr uint32_t m_vecItemStockInfo = 0x728; // C_UtlVectorEmbeddedNetworkVar< CDOTA_ItemStockInfo >
		constexpr uint32_t m_AssassinMiniGameNetData = 0x778; // DOTA_AssassinMinigameNetworkState
		constexpr uint32_t m_nGameWinner = 0x788; // int32
		constexpr uint32_t m_unMatchID64 = 0x790; // MatchID_t
		constexpr uint32_t m_bMatchSignoutComplete = 0x798; // bool
		constexpr uint32_t m_hSideShop1 = 0x79c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hSideShop2 = 0x7a0; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hSecretShop1 = 0x7a4; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hSecretShop2 = 0x7a8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hTeamFountains = 0x7ac; // CHandle< C_BaseEntity >[14]
		constexpr uint32_t m_hTeamForts = 0x7e4; // CHandle< C_BaseEntity >[14]
		constexpr uint32_t m_hTeamShops = 0x81c; // CHandle< C_BaseEntity >[14]
		constexpr uint32_t m_hAnnouncerGood = 0x854; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerBad = 0x858; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerSpectator = 0x85c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerGood_KillingSpree = 0x860; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerBad_KillingSpree = 0x864; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerSpectator_KillingSpree = 0x868; // CHandle< C_BaseEntity >
		constexpr uint32_t m_arrTier1TowerDestroyed = 0x86c; // bool[14]
		constexpr uint32_t m_arrTier2TowerDestroyed = 0x87a; // bool[14]
		constexpr uint32_t m_arrTier3TowerDestroyed = 0x888; // bool[14]
		constexpr uint32_t m_bTier1TowerDestroyed = 0x896; // bool
		constexpr uint32_t m_bTier2TowerDestroyed = 0x897; // bool
		constexpr uint32_t m_bTier3TowerDestroyed = 0x898; // bool
		constexpr uint32_t m_fTimeOfDay = 0x89c; // float32
		constexpr uint32_t m_iNetTimeOfDay = 0x8a0; // int32
		constexpr uint32_t m_nLoadedPlayers = 0x8a4; // int32
		constexpr uint32_t m_nExpectedPlayers = 0x8a8; // int32
		constexpr uint32_t m_iMinimapDebugGridState = 0x8b8; // int32
		constexpr uint32_t m_iFoWFrameNumber = 0x930; // int32
		constexpr uint32_t m_vWeatherWindDirection = 0x934; // Vector
		constexpr uint32_t m_vecRequiredPlaytestHeroesStorage = 0x940; // int32[24]
		constexpr uint32_t m_vecRecommendedPlaytestHeroesStorage = 0x9a0; // int32[24]
		constexpr uint32_t m_bAllRequiredPlaytestHeroesPicked = 0xa00; // bool
		constexpr uint32_t m_nLastPlaytestPickPhase = 0xa04; // int32
		constexpr uint32_t m_nCustomGameFowTeamCount = 0xa08; // int32
		constexpr uint32_t m_bUseAlternateABRules = 0xa0c; // bool
		constexpr uint32_t m_bLobbyIsAssociatedWithGame = 0xa0d; // bool
		constexpr uint32_t m_BotDebugTimer = 0xa10; // CountdownTimer
		constexpr uint32_t m_BotDebugPushLane = 0xa28; // uint8[18]
		constexpr uint32_t m_BotDebugDefendLane = 0xa3a; // uint8[18]
		constexpr uint32_t m_BotDebugFarmLane = 0xa4c; // uint8[6]
		constexpr uint32_t m_BotDebugRoam = 0xa52; // uint8[8]
		constexpr uint32_t m_hBotDebugRoamTarget = 0xa5c; // CHandle< C_BaseEntity >[2]
		constexpr uint32_t m_BotDebugRoshan = 0xa64; // uint8[2]
		constexpr uint32_t m_nRoshanRespawnPhase = 0xa68; // ERoshanSpawnPhase
		constexpr uint32_t m_flRoshanRespawnPhaseEndTime = 0xa6c; // GameTime_t
		constexpr uint32_t m_AbilityDraftAbilities = 0xa70; // C_UtlVectorEmbeddedNetworkVar< CDOTA_AbilityDraftAbilityState >
		constexpr uint32_t m_bAbilityDraftCurrentPlayerHasPicked = 0xac0; // bool
		constexpr uint32_t m_nAbilityDraftPlayerTracker = 0xac4; // int32
		constexpr uint32_t m_nAbilityDraftRoundNumber = 0xac8; // int32
		constexpr uint32_t m_nAbilityDraftAdvanceSteps = 0xacc; // int32
		constexpr uint32_t m_nAbilityDraftPhase = 0xad0; // int32
		constexpr uint32_t m_nAbilityDraftHeroesChosen = 0xad4; // int32[13]
		constexpr uint32_t m_vecARDMHeroes = 0xb08; // CUtlVector< KeyValues* >[2]
		constexpr uint32_t m_nARDMHeroesPrecached = 0xb38; // int32
		constexpr uint32_t m_fLastARDMPrecache = 0xb3c; // float32
		constexpr uint32_t m_nAllDraftPhase = 0xb40; // int32
		constexpr uint32_t m_bAllDraftRadiantFirst = 0xb44; // bool
		constexpr uint32_t m_bAllowOverrideVPK = 0xb45; // bool
		constexpr uint32_t m_nARDMHeroesRemaining = 0xb48; // int32[2]
		constexpr uint32_t m_bUpdateHeroStatues = 0xb50; // bool
		constexpr uint32_t m_bExperimentalGameplay = 0xb68; // bool
		constexpr uint32_t m_vecPlayerMMR = 0xba8; // CUtlVector< int32 >
		constexpr uint32_t m_lobbyType = 0xbc0; // uint32
		constexpr uint32_t m_lobbyLeagueID = 0xbc4; // LeagueID_t
		constexpr uint32_t m_lobbyGameName = 0xbc8; // char[256]
		constexpr uint32_t m_vecHeroStatueLiked = 0xcc8; // C_UtlVectorEmbeddedNetworkVar< CHeroStatueLiked >
		constexpr uint32_t m_CustomGameTeamMaxPlayers = 0xd18; // int32[14]
		constexpr uint32_t m_iMutations = 0xd50; // int32[5]
		constexpr uint32_t m_vecIngameEvents = 0xd68; // C_NetworkUtlVectorBase< CHandle< C_IngameEvent_Base > >
		constexpr uint32_t m_nPrimaryIngameEventIndex = 0xd80; // int8
		constexpr uint32_t m_hObsoleteIngameEvent = 0xd84; // CHandle< C_IngameEvent_Base >
		constexpr uint32_t m_nOfrendaPledges = 0xd88; // uint32
		constexpr uint32_t m_nRadiantOfrendas = 0xd8c; // uint32
		constexpr uint32_t m_nDireOfrendas = 0xd90; // uint32
		constexpr uint32_t m_bOfrendaEnabled = 0xd94; // bool
		constexpr uint32_t m_NeutralSpawnBoxes = 0xdc8; // C_NetworkUtlVectorBase< NeutralSpawnBoxes_t >
		constexpr uint32_t m_flLastPerfSampleTime = 0x1d98; // float64
		constexpr uint32_t m_flLastPerfSampleSendTime = 0x1da0; // float64
		constexpr uint32_t m_bDidSeeStrategyTime = 0x1da8; // bool
		constexpr uint32_t m_flLastUnfocusedSleepTime = 0xab00; // float64
	}
	namespace CGameSceneNode {
		constexpr uint32_t m_bDirtyHierarchy = 0x0; // bitfield:1
		constexpr uint32_t m_nodeToWorld = 0x10; // CTransform
		constexpr uint32_t m_pOwner = 0x30; // CEntityInstance*
		constexpr uint32_t m_pParent = 0x38; // CGameSceneNode*
		constexpr uint32_t m_pChild = 0x40; // CGameSceneNode*
		constexpr uint32_t m_pNextSibling = 0x48; // CGameSceneNode*
		constexpr uint32_t m_hParent = 0x70; // CGameSceneNodeHandle
		constexpr uint32_t m_vecOrigin = 0x80; // CNetworkOriginCellCoordQuantizedVector
		constexpr uint32_t m_angRotation = 0xb8; // QAngle
		constexpr uint32_t m_flScale = 0xc4; // float32
		constexpr uint32_t m_vecAbsOrigin = 0xc8; // Vector
		constexpr uint32_t m_angAbsRotation = 0xd4; // QAngle
		constexpr uint32_t m_flAbsScale = 0xe0; // float32
		constexpr uint32_t m_nParentAttachmentOrBone = 0xe4; // int16
		constexpr uint32_t m_bDebugAbsOriginChanges = 0xe6; // bool
		constexpr uint32_t m_bDormant = 0xe7; // bool
		constexpr uint32_t m_bForceParentToBeNetworked = 0xe8; // bool
		constexpr uint32_t m_nHierarchicalDepth = 0xeb; // uint8
		constexpr uint32_t m_nHierarchyType = 0xec; // uint8
		constexpr uint32_t m_nDoNotSetAnimTimeInInvalidatePhysicsCount = 0xed; // uint8
		constexpr uint32_t m_name = 0xf0; // CUtlStringToken
		constexpr uint32_t m_hierarchyAttachName = 0x130; // CUtlStringToken
		constexpr uint32_t m_flZOffset = 0x134; // float32
		constexpr uint32_t m_vRenderOrigin = 0x138; // Vector
	}
	namespace GameTime_t {
		constexpr uint32_t m_Value = 0x0; // float32
	}
	namespace C_DOTA_Item_EmptyBottle {
		constexpr uint32_t m_iStoredRuneType = 0x630; // int32
		constexpr uint32_t m_fStoredRuneTime = 0x634; // GameTime_t
		constexpr uint32_t rune_expire_time = 0x638; // float32
	}
}