#pragma once
#include <cstdint>
namespace Netvars {
	namespace C_DOTA_BaseNPC_Hero {
		constexpr uint32_t m_bBuybackDisabled = 0x0; // bitfield:1
		constexpr uint32_t m_iCurrentXP = 0x1778; // int32
		constexpr uint32_t m_iAbilityPoints = 0x177c; // int32
		constexpr uint32_t m_flRespawnTime = 0x1780; // GameTime_t
		constexpr uint32_t m_flRespawnTimePenalty = 0x1784; // float32
		constexpr uint32_t m_flStrength = 0x1788; // float32
		constexpr uint32_t m_flAgility = 0x178c; // float32
		constexpr uint32_t m_flIntellect = 0x1790; // float32
		constexpr uint32_t m_flStrengthTotal = 0x1794; // float32
		constexpr uint32_t m_flAgilityTotal = 0x1798; // float32
		constexpr uint32_t m_flIntellectTotal = 0x179c; // float32
		constexpr uint32_t m_flDeathTime = 0x17a0; // GameTime_t
		constexpr uint32_t m_iRecentDamage = 0x17a4; // int32
		constexpr uint32_t m_fPainFactor = 0x17a8; // float32
		constexpr uint32_t m_fTargetPainFactor = 0x17ac; // float32
		constexpr uint32_t m_bLifeState = 0x17b0; // bool
		constexpr uint32_t m_nFXStunIndex = 0x17b4; // ParticleIndex_t
		constexpr uint32_t m_nFXSilenceIndex = 0x17b8; // ParticleIndex_t
		constexpr uint32_t m_nFXDeathIndex = 0x17bc; // ParticleIndex_t
		constexpr uint32_t m_iPlayerID = 0x17e0; // PlayerID_t
		constexpr uint32_t m_hReplicatingOtherHeroModel = 0x17e4; // CHandle< C_DOTA_BaseNPC_Hero >
		constexpr uint32_t m_bReincarnating = 0x17e8; // bool
		constexpr uint32_t m_bCustomKillEffect = 0x17e9; // bool
		constexpr uint32_t m_flSpawnedAt = 0x17ec; // GameTime_t
		constexpr uint32_t m_bScriptDisableRespawns = 0x17f0; // bool
		constexpr uint32_t m_iPrimaryAttribute = 0x17f4; // int32
		constexpr uint32_t m_nLastDrawnHealth = 0x17f8; // int32
		constexpr uint32_t m_flHurtAmount = 0x17fc; // float32
		constexpr uint32_t m_flLastHurtTime = 0x1800; // GameTime_t
		constexpr uint32_t m_flHurtDecayRate = 0x1804; // float32
		constexpr uint32_t m_flLastHealTime = 0x1808; // GameTime_t
		constexpr uint32_t m_flLastTreeShakeTime = 0x180c; // GameTime_t
		constexpr uint32_t m_CenterOnHeroCooldownTimer = 0x1810; // CountdownTimer
		constexpr uint32_t m_CombinedModels = 0x1a30; // CStrongHandle< InfoForResourceTypeCModel >[4]
		constexpr uint32_t m_nCurrentCombinedModelIndex = 0x1a50; // int32
		constexpr uint32_t m_nPendingCombinedModelIndex = 0x1a54; // int32
		constexpr uint32_t m_iHeroID = 0x1a58; // int32
		constexpr uint32_t m_flCheckLegacyItemsAt = 0x1a5c; // float32
		constexpr uint32_t m_bDisplayAdditionalHeroes = 0x1a60; // bool
		constexpr uint32_t m_CombinedParticleModels = 0x1a70; // CStrongHandle< InfoForResourceTypeCModel >[4]
		constexpr uint32_t m_vecAttachedParticleIndeces = 0x1a90; // CUtlVector< ParticleIndex_t >
		constexpr uint32_t m_hPets = 0x1aa8; // CUtlVector< CHandle< C_BaseEntity > >
		constexpr uint32_t m_nKillStreakFX = 0x1ac0; // ParticleIndex_t
		constexpr uint32_t m_nKillStreakFXTier = 0x1ac4; // int32
	}
	namespace CEntityIdentity {
		constexpr uint32_t m_nameStringableIndex = 0x14; // int32
		constexpr uint32_t m_name = 0x18; // CUtlSymbolLarge
		constexpr uint32_t m_designerName = 0x20; // CUtlSymbolLarge
		constexpr uint32_t m_flags = 0x30; // uint32
		constexpr uint32_t m_worldGroupId = 0x38; // WorldGroupId_t
		constexpr uint32_t m_fDataObjectTypes = 0x3c; // uint32
		constexpr uint32_t m_PathIndex = 0x40; // ChangeAccessorFieldPathIndex_t
		constexpr uint32_t m_pPrev = 0x58; // CEntityIdentity*
		constexpr uint32_t m_pNext = 0x60; // CEntityIdentity*
		constexpr uint32_t m_pPrevByClass = 0x68; // CEntityIdentity*
		constexpr uint32_t m_pNextByClass = 0x70; // CEntityIdentity*
	}
	namespace C_BaseEntity {
		constexpr uint32_t m_CBodyComponent = 0x30; // CBodyComponent*
		constexpr uint32_t m_NetworkTransmitComponent = 0x38; // CNetworkTransmitComponent
		constexpr uint32_t m_nLastThinkTick = 0x308; // GameTick_t
		constexpr uint32_t m_pGameSceneNode = 0x310; // CGameSceneNode*
		constexpr uint32_t m_pRenderComponent = 0x318; // CRenderComponent*
		constexpr uint32_t m_pCollision = 0x320; // CCollisionProperty*
		constexpr uint32_t m_iMaxHealth = 0x328; // int32
		constexpr uint32_t m_iHealth = 0x32c; // int32
		constexpr uint32_t m_lifeState = 0x330; // uint8
		constexpr uint32_t m_takedamage = 0x331; // DamageOptions_t
		constexpr uint32_t m_bTakesDamage = 0x332; // bool
		constexpr uint32_t m_nTakeDamageFlags = 0x334; // TakeDamageFlags_t
		constexpr uint32_t m_ubInterpolationFrame = 0x338; // uint8
		constexpr uint32_t m_hSceneObjectController = 0x33c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_nNoInterpolationTick = 0x340; // int32
		constexpr uint32_t m_nVisibilityNoInterpolationTick = 0x344; // int32
		constexpr uint32_t m_flProxyRandomValue = 0x348; // float32
		constexpr uint32_t m_iEFlags = 0x34c; // int32
		constexpr uint32_t m_nWaterType = 0x350; // uint8
		constexpr uint32_t m_bInterpolateEvenWithNoModel = 0x351; // bool
		constexpr uint32_t m_bPredictionEligible = 0x352; // bool
		constexpr uint32_t m_bApplyLayerMatchIDToModel = 0x353; // bool
		constexpr uint32_t m_tokLayerMatchID = 0x354; // CUtlStringToken
		constexpr uint32_t m_nSubclassID = 0x358; // CUtlStringToken
		constexpr uint32_t m_nSimulationTick = 0x368; // int32
		constexpr uint32_t m_iCurrentThinkContext = 0x36c; // int32
		constexpr uint32_t m_aThinkFunctions = 0x370; // CUtlVector< thinkfunc_t >
		constexpr uint32_t m_flAnimTime = 0x388; // float32
		constexpr uint32_t m_flSimulationTime = 0x38c; // float32
		constexpr uint32_t m_nSceneObjectOverrideFlags = 0x390; // uint8
		constexpr uint32_t m_bHasSuccessfullyInterpolated = 0x391; // bool
		constexpr uint32_t m_bHasAddedVarsToInterpolation = 0x392; // bool
		constexpr uint32_t m_bRenderEvenWhenNotSuccessfullyInterpolated = 0x393; // bool
		constexpr uint32_t m_nInterpolationLatchDirtyFlags = 0x394; // int32[2]
		constexpr uint32_t m_ListEntry = 0x39c; // uint16[11]
		constexpr uint32_t m_flCreateTime = 0x3b4; // GameTime_t
		constexpr uint32_t m_flSpeed = 0x3b8; // float32
		constexpr uint32_t m_EntClientFlags = 0x3bc; // uint16
		constexpr uint32_t m_bClientSideRagdoll = 0x3be; // bool
		constexpr uint32_t m_iTeamNum = 0x3bf; // uint8
		constexpr uint32_t m_spawnflags = 0x3c0; // uint32
		constexpr uint32_t m_nNextThinkTick = 0x3c4; // GameTick_t
		constexpr uint32_t m_fFlags = 0x3c8; // uint32
		constexpr uint32_t m_vecAbsVelocity = 0x3cc; // Vector
		constexpr uint32_t m_vecVelocity = 0x3d8; // CNetworkVelocityVector
		constexpr uint32_t m_hEffectEntity = 0x408; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hOwnerEntity = 0x40c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_MoveCollide = 0x410; // MoveCollide_t
		constexpr uint32_t m_MoveType = 0x411; // MoveType_t
		constexpr uint32_t m_flWaterLevel = 0x414; // float32
		constexpr uint32_t m_fEffects = 0x418; // uint32
		constexpr uint32_t m_hGroundEntity = 0x41c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_flFriction = 0x420; // float32
		constexpr uint32_t m_flElasticity = 0x424; // float32
		constexpr uint32_t m_flGravityScale = 0x428; // float32
		constexpr uint32_t m_flTimeScale = 0x42c; // float32
		constexpr uint32_t m_bSimulatedEveryTick = 0x430; // bool
		constexpr uint32_t m_bAnimatedEveryTick = 0x431; // bool
		constexpr uint32_t m_flNavIgnoreUntilTime = 0x434; // GameTime_t
		constexpr uint32_t m_hThink = 0x438; // uint16
		constexpr uint32_t m_fBBoxVisFlags = 0x448; // uint8
		constexpr uint32_t m_bPredictable = 0x449; // bool
		constexpr uint32_t m_bRenderWithViewModels = 0x44a; // bool
		constexpr uint32_t m_nSplitUserPlayerPredictionSlot = 0x44c; // CSplitScreenSlot
		constexpr uint32_t m_nFirstPredictableCommand = 0x450; // int32
		constexpr uint32_t m_nLastPredictableCommand = 0x454; // int32
		constexpr uint32_t m_hOldMoveParent = 0x458; // CHandle< C_BaseEntity >
		constexpr uint32_t m_Particles = 0x460; // CParticleProperty
		constexpr uint32_t m_vecPredictedScriptFloats = 0x488; // CUtlVector< float32 >
		constexpr uint32_t m_vecPredictedScriptFloatIDs = 0x4a0; // CUtlVector< int32 >
		constexpr uint32_t m_nNextScriptVarRecordID = 0x4d0; // int32
		constexpr uint32_t m_vecAngVelocity = 0x4e0; // QAngle
		constexpr uint32_t m_DataChangeEventRef = 0x4ec; // int32
		constexpr uint32_t m_dependencies = 0x4f0; // CUtlVector< CEntityHandle >
		constexpr uint32_t m_nCreationTick = 0x508; // int32
		constexpr uint32_t m_bAnimTimeChanged = 0x521; // bool
		constexpr uint32_t m_bSimulationTimeChanged = 0x522; // bool
		constexpr uint32_t m_sUniqueHammerID = 0x530; // CUtlString
	}
	namespace C_EconEntity {
		constexpr uint32_t m_AttributeManager = 0x978; // CAttributeContainer
		constexpr uint32_t m_bClientside = 0xaa0; // bool
		constexpr uint32_t m_nDisableMode = 0xaa4; // EconEntityParticleDisableMode_t
		constexpr uint32_t m_bParticleSystemsCreated = 0xaa8; // bool
		constexpr uint32_t m_bForceDestroyAttachedParticlesImmediately = 0xaa9; // bool
		constexpr uint32_t m_vecAttachedParticles = 0xab0; // CUtlVector< C_EconEntity::AttachedParticleInfo_t >
		constexpr uint32_t m_hViewmodelAttachment = 0xac8; // CHandle< CBaseAnimatingActivity >
		constexpr uint32_t m_iOldTeam = 0xacc; // int32
		constexpr uint32_t m_bAttachmentDirty = 0xad0; // bool
		constexpr uint32_t m_iOldStyle = 0xad1; // style_index_t
		constexpr uint32_t m_hOldProvidee = 0xad4; // CHandle< C_BaseEntity >
		constexpr uint32_t m_vecAttachedModels = 0xad8; // CUtlVector< C_EconEntity::AttachedModelData_t >
	}
	namespace C_DOTA_Item {
		constexpr uint32_t m_bCombinable = 0x5b0; // bool
		constexpr uint32_t m_bPermanent = 0x5b1; // bool
		constexpr uint32_t m_bStackable = 0x5b2; // bool
		constexpr uint32_t m_iStackableMax = 0x5b4; // int32
		constexpr uint32_t m_bRecipe = 0x5b8; // bool
		constexpr uint32_t m_bRecipeConsumesCharges = 0x5b9; // bool
		constexpr uint32_t m_iSharability = 0x5bc; // int32
		constexpr uint32_t m_bDroppable = 0x5c0; // bool
		constexpr uint32_t m_bPurchasable = 0x5c1; // bool
		constexpr uint32_t m_bSellable = 0x5c2; // bool
		constexpr uint32_t m_bInitiallySellable = 0x5c3; // bool
		constexpr uint32_t m_bForceUnsellable = 0x5c4; // bool
		constexpr uint32_t m_bRequiresCharges = 0x5c5; // bool
		constexpr uint32_t m_bDisplayCharges = 0x5c6; // bool
		constexpr uint32_t m_bHideCharges = 0x5c7; // bool
		constexpr uint32_t m_bKillable = 0x5c8; // bool
		constexpr uint32_t m_bGloballyCombinable = 0x5c9; // bool
		constexpr uint32_t m_bDisassemblable = 0x5ca; // bool
		constexpr uint32_t m_bIsNeutralDrop = 0x5cb; // bool
		constexpr uint32_t m_nNeutralDropTeam = 0x5cc; // int32
		constexpr uint32_t m_bAlertable = 0x5d0; // bool
		constexpr uint32_t m_iInitialCharges = 0x5d4; // int32
		constexpr uint32_t m_bCastOnPickup = 0x5d8; // bool
		constexpr uint32_t m_bOnlyPlayerHeroPickup = 0x5d9; // bool
		constexpr uint32_t m_bCreepHeroPickup = 0x5da; // bool
		constexpr uint32_t m_iValuelessCharges = 0x5dc; // int32
		constexpr uint32_t m_iCurrentCharges = 0x5e0; // int32
		constexpr uint32_t m_iSecondaryCharges = 0x5e4; // int32
		constexpr uint32_t m_iMaxCharges = 0x5e8; // int32
		constexpr uint32_t m_bCombineLocked = 0x5ec; // bool
		constexpr uint32_t m_flPurchaseTime = 0x5f0; // GameTime_t
		constexpr uint32_t m_flAssembledTime = 0x5f4; // GameTime_t
		constexpr uint32_t m_bPurchasedWhileDead = 0x5f8; // bool
		constexpr uint32_t m_bCanBeUsedOutOfInventory = 0x5f9; // bool
		constexpr uint32_t m_bItemEnabled = 0x5fa; // bool
		constexpr uint32_t m_flEnableTime = 0x5fc; // GameTime_t
		constexpr uint32_t m_flReclaimTime = 0x600; // GameTime_t
		constexpr uint32_t m_bDisplayOwnership = 0x604; // bool
		constexpr uint32_t m_bShowOnMinimap = 0x605; // bool
		constexpr uint32_t m_flMinimapIconSize = 0x608; // float32
		constexpr uint32_t m_bIsUpgradeable = 0x60c; // bool
		constexpr uint32_t m_nUpgradeProgress = 0x610; // int32
		constexpr uint32_t m_nUpgradeGoal = 0x614; // int32
		constexpr uint32_t m_hOldOwnerEntity = 0x618; // CHandle< C_BaseEntity >
		constexpr uint32_t m_iOldCharges = 0x61c; // int32
		constexpr uint32_t m_iPlayerOwnerID = 0x620; // PlayerID_t
		constexpr uint32_t m_vecPreGameTransferPlayerIDs = 0x628; // C_NetworkUtlVectorBase< uint8 >
	}
	namespace PlayerResourcePlayerData_t {
		constexpr uint32_t m_bIsValid = 0x30; // bool
		constexpr uint32_t m_iszPlayerName = 0x38; // CUtlSymbolLarge
		constexpr uint32_t m_iPlayerTeam = 0x40; // int32
		constexpr uint32_t m_bFullyJoinedServer = 0x44; // bool
		constexpr uint32_t m_bFakeClient = 0x45; // bool
		constexpr uint32_t m_bIsBroadcaster = 0x46; // bool
		constexpr uint32_t m_iBroadcasterChannel = 0x48; // uint32
		constexpr uint32_t m_iBroadcasterChannelSlot = 0x4c; // uint32
		constexpr uint32_t m_bIsBroadcasterChannelCameraman = 0x50; // bool
		constexpr uint32_t m_iConnectionState = 0x54; // int32
		constexpr uint32_t m_iPlayerSteamID = 0x58; // uint64
		constexpr uint32_t m_eCoachTeam = 0x60; // DOTATeam_t
		constexpr uint32_t m_vecPrivateCoachPlayerIDs = 0x68; // C_NetworkUtlVectorBase< PlayerID_t >
		constexpr uint32_t m_unCoachRating = 0x80; // uint32
		constexpr uint32_t m_eLiveSpectatorTeam = 0x84; // DOTATeam_t
		constexpr uint32_t m_nLiveSpectatorSpectatedHeroIndex = 0x88; // int32
		constexpr uint32_t m_bIsPlusSubscriber = 0x8c; // bool
		constexpr uint32_t m_bWasMVPLastGame = 0x8d; // bool
		constexpr uint32_t m_nCavernCrawlMapVariant = 0x8e; // CavernCrawlMapVariant_t
		constexpr uint32_t m_eAccoladeType = 0x90; // int32[3]
		constexpr uint32_t m_unAccoladeData = 0xa0; // uint64[3]
		constexpr uint32_t m_iRankTier = 0xb8; // int32
		constexpr uint32_t m_iTitle = 0xbc; // int32
		constexpr uint32_t m_unFavTeamPacked = 0xc0; // uint64
		constexpr uint32_t m_nPlayerSlot = 0xc8; // CPlayerSlot
		constexpr uint32_t m_bIsBot = 0xcc; // bool
		constexpr uint32_t m_bHasNeutralTier = 0xcd; // bool[5]
		constexpr uint32_t m_bHasRedeemedNeutralTier = 0xd2; // bool[5]
		constexpr uint32_t m_nCommLevel = 0xd8; // int32
		constexpr uint32_t m_nBehaviorLevel = 0xdc; // int32
		constexpr uint32_t m_flLastCommsTime = 0xe0; // float32
	}
	namespace C_DOTABaseAbility {
		constexpr uint32_t m_bAuxCastState = 0x540; // bool
		constexpr uint32_t m_iEnemyLevel = 0x544; // int32
		constexpr uint32_t m_iMaxLevel = 0x548; // int32
		constexpr uint32_t m_bCanLearn = 0x54c; // bool
		constexpr uint32_t m_flUpgradeBlend = 0x550; // float32
		constexpr uint32_t m_bUpgradedDuringQuickcastPreview = 0x554; // bool
		constexpr uint32_t m_bConsiderOvershootInGetCastRange = 0x555; // bool
		constexpr uint32_t m_bRefCountsModifiers = 0x556; // bool
		constexpr uint32_t m_bHidden = 0x557; // bool
		constexpr uint32_t m_bOldHidden = 0x558; // bool
		constexpr uint32_t m_bActivated = 0x559; // bool
		constexpr uint32_t m_bOldActivated = 0x55a; // bool
		constexpr uint32_t m_nAbilityBarType = 0x55c; // AbilityBarType_t
		constexpr uint32_t m_iDirtyButtons = 0x560; // int32
		constexpr uint32_t m_bPerformDirtyParity = 0x564; // bool
		constexpr uint32_t m_iLevel = 0x568; // int32
		constexpr uint32_t m_bAbilityLevelDirty = 0x56c; // bool
		constexpr uint32_t m_bToggleState = 0x56d; // bool
		constexpr uint32_t m_flAbilityMuteDuration = 0x570; // float32
		constexpr uint32_t m_bInAbilityPhase = 0x574; // bool
		constexpr uint32_t m_fCooldown = 0x578; // float32
		constexpr uint32_t m_flCooldownLength = 0x57c; // float32
		constexpr uint32_t m_iManaCost = 0x580; // int32
		constexpr uint32_t m_bAutoCastState = 0x584; // bool
		constexpr uint32_t m_bAltCastState = 0x585; // bool
		constexpr uint32_t m_flChannelStartTime = 0x588; // GameTime_t
		constexpr uint32_t m_flCastStartTime = 0x58c; // GameTime_t
		constexpr uint32_t m_bInIndefiniteCooldown = 0x590; // bool
		constexpr uint32_t m_bFrozenCooldown = 0x591; // bool
		constexpr uint32_t m_flOverrideCastPoint = 0x594; // float32
		constexpr uint32_t m_bStolen = 0x598; // bool
		constexpr uint32_t m_bStealable = 0x599; // bool
		constexpr uint32_t m_bReplicated = 0x59a; // bool
		constexpr uint32_t m_nAbilityCurrentCharges = 0x59c; // int32
		constexpr uint32_t m_fAbilityChargeRestoreTimeRemaining = 0x5a0; // float32
		constexpr uint32_t m_bUpgradeRecommended = 0x5a4; // bool
		constexpr uint32_t m_nMaxLevelOverride = 0x5a8; // int32
		constexpr uint32_t m_flLastCastClickTime = 0x5ac; // float32
	}
	namespace C_DOTA_Item_PowerTreads {
		constexpr uint32_t m_iStat = 0x648; // int32
	}
	namespace C_DOTA_BaseNPC {
		constexpr uint32_t m_bIsPhantom = 0xa30; // bool
		constexpr uint32_t m_iUnitType = 0xa34; // uint32
		constexpr uint32_t m_bSelectionRingVisible = 0xa48; // bool
		constexpr uint32_t m_iCurrentLevel = 0xa4c; // int32
		constexpr uint32_t m_bIsAncient = 0xa50; // bool
		constexpr uint32_t m_bIsBossCreature = 0xa51; // bool
		constexpr uint32_t m_bStolenScepter = 0xa52; // bool
		constexpr uint32_t m_bIsNeutralUnitType = 0xa53; // bool
		constexpr uint32_t m_bSelectOnSpawn = 0xa54; // bool
		constexpr uint32_t m_bCachedReplicatedMorphlingIllusion = 0xa55; // bool
		constexpr uint32_t m_bIgnoreAddSummonedToSelection = 0xa56; // bool
		constexpr uint32_t m_bConsideredHero = 0xa57; // bool
		constexpr uint32_t m_bUsesConstantGesture = 0xa58; // bool
		constexpr uint32_t m_bUseHeroAbilityNumbers = 0xa59; // bool
		constexpr uint32_t m_bHasSharedAbilities = 0xa5a; // bool
		constexpr uint32_t m_bIsSummoned = 0xa5b; // bool
		constexpr uint32_t m_bCanBeDominated = 0xa5c; // bool
		constexpr uint32_t m_bHasUpgradeableAbilities = 0xa5d; // bool
		constexpr uint32_t m_flHealthThinkRegen = 0xa60; // float32
		constexpr uint32_t m_iIsControllableByPlayer64 = 0xa68; // uint64
		constexpr uint32_t m_nHealthBarOffsetOverride = 0xa70; // int32
		constexpr uint32_t m_bCanRespawn = 0xa74; // bool
		constexpr uint32_t m_iAttackRange = 0xa78; // int32
		constexpr uint32_t m_colorGemColor = 0xa7c; // Color
		constexpr uint32_t m_bHasColorGem = 0xa80; // bool
		constexpr uint32_t m_nFXDeniableIndex = 0xa84; // ParticleIndex_t
		constexpr uint32_t m_iMoveSpeed = 0xa88; // int32
		constexpr uint32_t m_iBaseAttackSpeed = 0xa8c; // int32
		constexpr uint32_t m_flBaseAttackTime = 0xa90; // float32
		constexpr uint32_t m_iUnitNameIndex = 0xa94; // int32
		constexpr uint32_t m_iHealthBarOffset = 0xa98; // int32
		constexpr uint32_t m_iHealthBarHighlightColor = 0xa9c; // Color
		constexpr uint32_t m_flMana = 0xaa0; // float32
		constexpr uint32_t m_flMaxMana = 0xaa4; // float32
		constexpr uint32_t m_flManaThinkRegen = 0xaa8; // float32
		constexpr uint32_t m_iBKBChargesUsed = 0xaac; // int32
		constexpr uint32_t m_iAeonChargesUsed = 0xab0; // int32
		constexpr uint32_t m_flRefresherUseTime = 0xab4; // GameTime_t
		constexpr uint32_t m_flRefresherLastCooldown = 0xab8; // float32
		constexpr uint32_t m_flLastDealtDamageTime = 0xabc; // GameTime_t
		constexpr uint32_t m_iBotDebugData = 0xac0; // int32
		constexpr uint32_t m_bIsIllusion = 0xac4; // bool
		constexpr uint32_t m_bHasClientSeenIllusionModifier = 0xac5; // bool
		constexpr uint32_t m_hAbilities = 0xac8; // CHandle< C_BaseEntity >[35]
		constexpr uint32_t m_flInvisibilityLevel = 0xb54; // float32
		constexpr uint32_t m_flHullRadius = 0xb58; // float32
		constexpr uint32_t m_flCollisionPadding = 0xb5c; // float32
		constexpr uint32_t m_flRingRadius = 0xb60; // float32
		constexpr uint32_t m_flProjectileCollisionSize = 0xb64; // float32
		constexpr uint32_t m_iszUnitName = 0xb68; // CUtlSymbolLarge
		constexpr uint32_t m_iszParticleFolder = 0xb70; // CUtlSymbolLarge
		constexpr uint32_t m_iszSoundSet = 0xb78; // CUtlSymbolLarge
		constexpr uint32_t m_iszSelectionGroup = 0xb80; // CUtlSymbolLarge
		constexpr uint32_t m_iszVoiceFile = 0xb88; // CUtlSymbolLarge
		constexpr uint32_t m_iszGameSoundsFile = 0xb90; // CUtlSymbolLarge
		constexpr uint32_t m_iszVoiceBackgroundSound = 0xb98; // CUtlSymbolLarge
		constexpr uint32_t m_iszIdleSoundLoop = 0xba0; // CUtlSymbolLarge
		constexpr uint32_t m_szUnitLabel = 0xba8; // CUtlString
		constexpr uint32_t m_szScaleset = 0xbb0; // CUtlString
		constexpr uint32_t m_nUnitLabelIndex = 0xbb8; // uint8
		constexpr uint32_t m_strAnimationModifier = 0xbc0; // CUtlString
		constexpr uint32_t m_TerrainSpecificFootstepEffect = 0xbc8; // CUtlString
		constexpr uint32_t m_bUseCustomTerrainWeatherEffect = 0xbd0; // bool
		constexpr uint32_t m_bHasClientSoundReplacement = 0xbd1; // bool
		constexpr uint32_t m_bHasClientReplacementParticle = 0xbd2; // bool
		constexpr uint32_t m_bResourcesLoaded = 0xbdc; // bool
		constexpr uint32_t m_flTauntCooldown = 0xbe0; // GameTime_t
		constexpr uint32_t m_flTauntCooldown2 = 0xbe4; // GameTime_t
		constexpr uint32_t m_iCurShop = 0xbe8; // DOTA_SHOP_TYPE
		constexpr uint32_t m_szCurShopEntName = 0xbf0; // CUtlSymbolLarge
		constexpr uint32_t m_iDayTimeVisionRange = 0xbf8; // int32
		constexpr uint32_t m_iNightTimeVisionRange = 0xbfc; // int32
		constexpr uint32_t m_iDamageMin = 0xc00; // int32
		constexpr uint32_t m_iDamageMax = 0xc04; // int32
		constexpr uint32_t m_iDamageBonus = 0xc08; // int32
		constexpr uint32_t m_iTaggedAsVisibleByTeam = 0xc0c; // int32
		constexpr uint32_t m_ModifierManager = 0xc10; // CDOTA_ModifierManager
		constexpr uint32_t m_Inventory = 0xeb8; // C_DOTA_UnitInventory
		constexpr uint32_t m_nUnitState64 = 0xf78; // uint64
		constexpr uint32_t m_nUnitDebuffState = 0xf88; // uint64
		constexpr uint32_t m_bHasInventory = 0xf90; // bool
		constexpr uint32_t m_iAcquisitionRange = 0xf94; // int32
		constexpr uint32_t m_FoWViewID = 0xf98; // int32
		constexpr uint32_t m_iPrevHealthPct = 0xf9c; // int32
		constexpr uint32_t m_iPrevLifeState = 0xfa0; // int32
		constexpr uint32_t m_iPrevTeam = 0xfa4; // int32
		constexpr uint32_t m_bPrevProvidesVision = 0xfa8; // bool
		constexpr uint32_t m_nPrevControllableMask = 0xfb0; // uint64
		constexpr uint32_t m_TagTime = 0xfc0; // CountdownTimer
		constexpr uint32_t m_ClickedTime = 0xfd8; // CountdownTimer
		constexpr uint32_t m_flIdleRunPoseStartTime = 0xff0; // GameTime_t[2]
		constexpr uint32_t m_flIdleRunPoseDuration = 0xff8; // float32[2]
		constexpr uint32_t m_bAnimationTransitionActive = 0x1000; // bool
		constexpr uint32_t m_nAnimationTransitionPoseParameters = 0x1004; // int32[2]
		constexpr uint32_t m_nAnimationTransitionInjuredPoseParameters = 0x100c; // int32[2]
		constexpr uint32_t m_nAnimationTransitionAggressivePoseParameters = 0x1014; // int32[2]
		constexpr uint32_t m_flTimeSinceLastAbilityNag = 0x1078; // GameTime_t
		constexpr uint32_t m_iAttackCapabilities = 0x107c; // int32
		constexpr uint32_t m_iSpecialAbility = 0x1080; // int32
		constexpr uint32_t m_iMoveCapabilities = 0x1084; // int32
		constexpr uint32_t m_nPlayerOwnerID = 0x1088; // PlayerID_t
		constexpr uint32_t m_flLastDamageTime = 0x108c; // GameTime_t
		constexpr uint32_t m_flLastAttackTime = 0x1090; // GameTime_t
		constexpr uint32_t m_iszMinimapIcon = 0x1098; // CUtlSymbolLarge
		constexpr uint32_t m_flMinimapIconSize = 0x10a8; // float32
		constexpr uint32_t m_bMinimapDisableTint = 0x10ac; // bool
		constexpr uint32_t m_bMinimapDisableRotation = 0x10ad; // bool
		constexpr uint32_t m_colorHeroGlow = 0x10ae; // Color
		constexpr uint32_t m_iNearShopMask = 0x10b4; // int32
		constexpr uint32_t m_nPoseParameterTurn = 0x10b8; // int32
		constexpr uint32_t m_nPoseParameterRun = 0x10bc; // int32
		constexpr uint32_t m_flLean = 0x10c0; // float32
		constexpr uint32_t m_flRun = 0x10c4; // float32
		constexpr uint32_t m_anglediff = 0x10c8; // int32
		constexpr uint32_t m_bInfoKeyActive = 0x10cc; // bool
		constexpr uint32_t m_bNewUpdateAssetModifiersNetworked = 0x10cd; // bool
		constexpr uint32_t m_nAssetModifiersLastUpdatedTick = 0x10d0; // GameTick_t
		constexpr uint32_t m_bSuppressGlow = 0x10d4; // bool
		constexpr uint32_t m_bWasSinking = 0x10d5; // bool
		constexpr uint32_t m_flRangeDisplayDist = 0x10d8; // float32
		constexpr uint32_t m_szDefaultIdle = 0x12c0; // CUtlSymbolLarge
		constexpr uint32_t m_szDefaultRareIdle = 0x12c8; // CUtlSymbolLarge
		constexpr uint32_t m_damagetimer = 0x12d0; // CountdownTimer
		constexpr uint32_t m_vRenderOrigin = 0x12e8; // Vector
		constexpr uint32_t m_fZDelta = 0x12f4; // float32
		constexpr uint32_t m_flDeathTime = 0x12f8; // GameTime_t
		constexpr uint32_t m_bBaseStatsChanged = 0x12fc; // bool
		constexpr uint32_t m_bNeedsSoundEmitterRefresh = 0x12fd; // bool
		constexpr uint32_t m_flPhysicalArmorValue = 0x1300; // float32
		constexpr uint32_t m_flMagicalResistanceValue = 0x1304; // float32
		constexpr uint32_t m_nPrevSequenceParity = 0x1308; // int32
		constexpr uint32_t m_flPrevInvisLevel = 0x13b0; // float32
		constexpr uint32_t m_nOriginalModelIndex = 0x13b8; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_nClientOriginalModelIndex = 0x13c0; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_nClientReplacementModelIndex = 0x13c8; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_bClientReplacementModelNeedsRebuild = 0x13d0; // bool
		constexpr uint32_t m_nClientReplacementModelReloadCount = 0x13d4; // int32
		constexpr uint32_t m_nUnitModelVariant = 0x13d8; // int8
		constexpr uint32_t m_nUnitModelVariantCount = 0x13d9; // int8
		constexpr uint32_t m_iPrevSequence = 0x13dc; // int32
		constexpr uint32_t m_pLastWeatherEffectName = 0x13e0; // char*
		constexpr uint32_t m_VoiceBackgroundSoundTimer = 0x13f0; // CountdownTimer
		constexpr uint32_t m_bIsWaitingToSpawn = 0x1408; // bool
		constexpr uint32_t m_nTotalDamageTaken = 0x1410; // int64
		constexpr uint32_t m_flManaRegen = 0x1418; // float32
		constexpr uint32_t m_flHealthRegen = 0x141c; // float32
		constexpr uint32_t m_bIsMoving = 0x1420; // bool
		constexpr uint32_t m_fRevealRadius = 0x1424; // float32
		constexpr uint32_t m_bCanUseWards = 0x1428; // bool
		constexpr uint32_t m_bCanUseAllItems = 0x1429; // bool
		constexpr uint32_t m_iXPBounty = 0x142c; // int32
		constexpr uint32_t m_iXPBountyExtra = 0x1430; // int32
		constexpr uint32_t m_iGoldBountyMin = 0x1434; // int32
		constexpr uint32_t m_iGoldBountyMax = 0x1438; // int32
		constexpr uint32_t m_hOwnerNPC = 0x143c; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hGoalEntity = 0x1440; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hNeutralSpawner = 0x1444; // CHandle< C_DOTA_NeutralSpawner >
		constexpr uint32_t m_hClientOverrideMaterial = 0x1448; // CStrongHandle< InfoForResourceTypeIMaterial2 >
		constexpr uint32_t m_bCombinerMaterialOverrideListChanged = 0x1450; // bool
		constexpr uint32_t m_nBaseModelMeshCount = 0x1454; // int32
		constexpr uint32_t m_combinerMaterialOverrideList = 0x1458; // CUtlVector< CStrongHandleCopyable< InfoForResourceTypeIMaterial2 > >
		constexpr uint32_t m_nArcanaLevel = 0x1470; // int8
		constexpr uint32_t m_nDefaultArcanaLevel = 0x1471; // int8
		constexpr uint32_t m_defaultColorGemColor = 0x1472; // Color
		constexpr uint32_t m_bHasBuiltWearableSpawnList = 0x1490; // bool
		constexpr uint32_t m_bHasCostume = 0x1491; // bool
		constexpr uint32_t m_bRecreateParticleSystemsOnModifiersChange = 0x1492; // bool
		constexpr uint32_t m_NetworkActivity = 0x15b0; // int32
		constexpr uint32_t m_PrevNetworkActivity = 0x15b4; // int32
		constexpr uint32_t m_NetworkSequenceIndex = 0x15b8; // int32
		constexpr uint32_t m_bShouldDoFlyHeightVisual = 0x15bc; // bool
		constexpr uint32_t m_flStartSequenceCycle = 0x15c0; // float32
		constexpr uint32_t m_ActivityModifiers = 0x15c8; // CUtlVector< CUtlSymbol >
		constexpr uint32_t m_hBackgroundSceneEnt = 0x15e0; // CHandle< C_SceneEntity >
		constexpr uint32_t m_hSpeakingSceneEnt = 0x15e4; // CHandle< C_SceneEntity >
		constexpr uint32_t m_hOldWearables = 0x15f8; // CUtlVector< CHandle< C_EconWearable > >
		constexpr uint32_t m_hOldWearableSkins = 0x1610; // CUtlVector< CUtlStringToken >
		constexpr uint32_t m_CustomHealthLabel = 0x1628; // char[256]
		constexpr uint32_t m_CustomHealthLabelColor = 0x1728; // Color
		constexpr uint32_t m_nWearableDefIndex = 0x172c; // item_definition_index_t
		constexpr uint32_t m_gibTintColor = 0x1731; // Color
		constexpr uint32_t m_bForceMaterialCombine = 0x1735; // bool
		constexpr uint32_t m_bShouldDrawParticlesWhileHidden = 0x1736; // bool
		constexpr uint32_t m_bIsClientThinkPending = 0x1737; // bool
		constexpr uint32_t m_bActivityModifiersDirty = 0x1738; // bool
		constexpr uint32_t m_bUnitModelVariantChanged = 0x1739; // bool
		constexpr uint32_t m_bWearablesAreTaunting = 0x173a; // bool
		constexpr uint32_t m_bShowCannotBeDisabledIcon = 0x1750; // bool
	}
	namespace CBasePlayerController {
		constexpr uint32_t m_nFinalPredictedTick = 0x540; // int32
		constexpr uint32_t m_CommandContext = 0x548; // C_CommandContext
		constexpr uint32_t m_nInButtonsWhichAreToggles = 0x5c0; // uint64
		constexpr uint32_t m_nTickBase = 0x5c8; // uint32
		constexpr uint32_t m_hPawn = 0x5cc; // CHandle< C_BasePlayerPawn >
		constexpr uint32_t m_hPredictedPawn = 0x5d0; // CHandle< C_BasePlayerPawn >
		constexpr uint32_t m_nSplitScreenSlot = 0x5d4; // CSplitScreenSlot
		constexpr uint32_t m_hSplitOwner = 0x5d8; // CHandle< CBasePlayerController >
		constexpr uint32_t m_hSplitScreenPlayers = 0x5e0; // CUtlVector< CHandle< CBasePlayerController > >
		constexpr uint32_t m_bIsHLTV = 0x5f8; // bool
		constexpr uint32_t m_iConnected = 0x5fc; // PlayerConnectedState
		constexpr uint32_t m_iszPlayerName = 0x600; // char[128]
		constexpr uint32_t m_steamID = 0x688; // uint64
		constexpr uint32_t m_bIsLocalPlayerController = 0x690; // bool
		constexpr uint32_t m_iDesiredFOV = 0x694; // uint32
	}
	namespace CEntityInstance {
		constexpr uint32_t m_iszPrivateVScripts = 0x8; // CUtlSymbolLarge
		constexpr uint32_t m_pEntity = 0x10; // CEntityIdentity*
		constexpr uint32_t m_CScriptComponent = 0x28; // CScriptComponent*
	}
	namespace C_NextBotCombatCharacter {
		constexpr uint32_t m_shadowTimer = 0x9f8; // CountdownTimer
		constexpr uint32_t m_bInFrustum = 0xa10; // bool
		constexpr uint32_t m_nInFrustumFrame = 0xa14; // int32
		constexpr uint32_t m_flFrustumDistanceSqr = 0xa18; // float32
		constexpr uint32_t m_nLod = 0xa1c; // uint8
	}
	namespace C_BaseCombatCharacter {
		constexpr uint32_t m_hMyWearables = 0x968; // C_NetworkUtlVectorBase< CHandle< C_EconWearable > >
		constexpr uint32_t m_bloodColor = 0x980; // int32
		constexpr uint32_t m_leftFootAttachment = 0x984; // AttachmentHandle_t
		constexpr uint32_t m_rightFootAttachment = 0x985; // AttachmentHandle_t
		constexpr uint32_t m_nWaterWakeMode = 0x988; // C_BaseCombatCharacter::WaterWakeMode_t
		constexpr uint32_t m_flWaterWorldZ = 0x98c; // float32
		constexpr uint32_t m_flWaterNextTraceTime = 0x990; // float32
		constexpr uint32_t m_flFieldOfView = 0x994; // float32
	}
	namespace C_BaseFlex {
		constexpr uint32_t m_flexWeight = 0x7f0; // C_NetworkUtlVectorBase< float32 >
		constexpr uint32_t m_vLookTargetPosition = 0x808; // Vector
		constexpr uint32_t m_blinktoggle = 0x820; // bool
		constexpr uint32_t m_nLastFlexUpdateFrameCount = 0x880; // int32
		constexpr uint32_t m_CachedViewTarget = 0x884; // Vector
		constexpr uint32_t m_nNextSceneEventId = 0x890; // uint32
		constexpr uint32_t m_iBlink = 0x894; // int32
		constexpr uint32_t m_blinktime = 0x898; // float32
		constexpr uint32_t m_prevblinktoggle = 0x89c; // bool
		constexpr uint32_t m_iMouthAttachment = 0x89d; // AttachmentHandle_t
		constexpr uint32_t m_iEyeAttachment = 0x89e; // AttachmentHandle_t
		constexpr uint32_t m_bResetFlexWeightsOnModelChange = 0x89f; // bool
		constexpr uint32_t m_nEyeOcclusionRendererBone = 0x8b8; // int32
		constexpr uint32_t m_mEyeOcclusionRendererCameraToBoneTransform = 0x8bc; // matrix3x4_t
		constexpr uint32_t m_vEyeOcclusionRendererHalfExtent = 0x8ec; // Vector
		constexpr uint32_t m_PhonemeClasses = 0x908; // C_BaseFlex::Emphasized_Phoneme[3]
	}
	namespace CBaseAnimatingActivity {
		constexpr uint32_t m_bShouldAnimateDuringGameplayPause = 0x7b8; // bool
		constexpr uint32_t m_bInitiallyPopulateInterpHistory = 0x7b9; // bool
		constexpr uint32_t m_pSuppressedAnimEventTags = 0x7c0; // CUtlVector< CUtlString >*
		constexpr uint32_t m_bHasAnimatedMaterialAttributes = 0x7c8; // bool
		constexpr uint32_t m_bSuppressAnimEventSounds = 0x7d8; // bool
	}
	namespace C_DOTA_UnitInventory {
		constexpr uint32_t m_SharedCooldownList = 0x8; // CUtlVector< sSharedCooldownInfo >
		constexpr uint32_t m_hItems = 0x20; // CHandle< C_BaseEntity >[19]
		constexpr uint32_t m_bItemQueried = 0x6c; // bool[21]
		constexpr uint32_t m_iParity = 0x84; // int32
		constexpr uint32_t m_hInventoryParent = 0x88; // CHandle< C_BaseEntity >
		constexpr uint32_t m_bIsActive = 0x8c; // bool
		constexpr uint32_t m_bStashEnabled = 0x8d; // bool
		constexpr uint32_t m_hTransientCastItem = 0x90; // CHandle< C_BaseEntity >
		constexpr uint32_t m_bSendChangedMsg = 0xb0; // bool
	}
	namespace C_BaseModelEntity {
		constexpr uint32_t m_CRenderComponent = 0x538; // CRenderComponent*
		constexpr uint32_t m_CHitboxComponent = 0x540; // CHitboxComponent
		constexpr uint32_t m_bInitModelEffects = 0x588; // bool
		constexpr uint32_t m_bIsStaticProp = 0x589; // bool
		constexpr uint32_t m_iViewerID = 0x58c; // int32
		constexpr uint32_t m_iTeamVisibilityBitmask = 0x590; // int32
		constexpr uint32_t m_nLastAddDecal = 0x594; // int32
		constexpr uint32_t m_nDecalsAdded = 0x598; // int32
		constexpr uint32_t m_iOldHealth = 0x59c; // int32
		constexpr uint32_t m_nRenderMode = 0x5a0; // RenderMode_t
		constexpr uint32_t m_bVisibilityDirtyFlag = 0x5a1; // bool
		constexpr uint32_t m_nRenderFX = 0x5a2; // RenderFx_t
		constexpr uint32_t m_bAllowFadeInView = 0x5a3; // bool
		constexpr uint32_t m_clrRender = 0x5a4; // Color
		constexpr uint32_t m_vecRenderAttributes = 0x5a8; // C_UtlVectorEmbeddedNetworkVar< EntityRenderAttribute_t >
		constexpr uint32_t m_LightGroup = 0x610; // CUtlStringToken
		constexpr uint32_t m_bRenderToCubemaps = 0x614; // bool
		constexpr uint32_t m_Collision = 0x618; // CCollisionProperty
		constexpr uint32_t m_Glow = 0x6c8; // CGlowProperty
		constexpr uint32_t m_flGlowBackfaceMult = 0x720; // float32
		constexpr uint32_t m_fadeMinDist = 0x724; // float32
		constexpr uint32_t m_fadeMaxDist = 0x728; // float32
		constexpr uint32_t m_flFadeScale = 0x72c; // float32
		constexpr uint32_t m_flShadowStrength = 0x730; // float32
		constexpr uint32_t m_nObjectCulling = 0x734; // uint8
		constexpr uint32_t m_nAddDecal = 0x738; // int32
		constexpr uint32_t m_vDecalPosition = 0x73c; // Vector
		constexpr uint32_t m_vDecalForwardAxis = 0x748; // Vector
		constexpr uint32_t m_flDecalHealBloodRate = 0x754; // float32
		constexpr uint32_t m_flDecalHealHeightRate = 0x758; // float32
		constexpr uint32_t m_ConfigEntitiesToPropagateMaterialDecalsTo = 0x760; // C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > >
		constexpr uint32_t m_vecViewOffset = 0x778; // CNetworkViewOffsetVector
		constexpr uint32_t m_pClientAlphaProperty = 0x7a8; // CClientAlphaProperty*
		constexpr uint32_t m_ClientOverrideTint = 0x7b0; // Color
		constexpr uint32_t m_bUseClientOverrideTint = 0x7b4; // bool
	}
	namespace C_DOTAPlayerController {
		constexpr uint32_t m_iMinimapMove = 0x750; // int32
		constexpr uint32_t m_pClickBehaviorKeys = 0x758; // KeyValues*
		constexpr uint32_t m_flCenterTime = 0x760; // GameTime_t
		constexpr uint32_t m_iConfirmationIndex = 0x764; // int32
		constexpr uint32_t m_bCenterOnHero = 0x768; // bool
		constexpr uint32_t m_bHeroAssigned = 0x769; // bool
		constexpr uint32_t m_nKeyBindHeroID = 0x76c; // int32
		constexpr uint32_t m_bUsingCameraMan = 0x770; // bool
		constexpr uint32_t m_bUsingAssistedCameraOperator = 0x771; // bool
		constexpr uint32_t m_nPlayerAssistFlags = 0x774; // int32
		constexpr uint32_t m_vLatestEvent = 0x778; // Vector
		constexpr uint32_t m_hFreeDrawAbility = 0x7a8; // CHandle< C_DOTABaseAbility >
		constexpr uint32_t m_vLastFreeDrawPosition = 0x7ac; // Vector
		constexpr uint32_t m_nPlayerID = 0x7b8; // PlayerID_t
		constexpr uint32_t m_hAssignedHero = 0x7bc; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hLastAssignedHero = 0x7c0; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hKillCamUnit = 0x7c4; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hPreviousKillCamUnit = 0x7c8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_flKillCamUnitReceivedTime = 0x7cc; // float32
		constexpr uint32_t m_nRareLineClickCount = 0x7d8; // int32
		constexpr uint32_t m_nRareLinesPlayed = 0x7dc; // int32
		constexpr uint32_t m_nRareLineGroup = 0x7e0; // int32
		constexpr uint32_t m_flLastRareLinePlayTime = 0x7e4; // float32
		constexpr uint32_t m_flLastUnitOrdersSendTime = 0x7e8; // float32
		constexpr uint32_t m_bTeleportRequiresHalt = 0x7ec; // bool
		constexpr uint32_t m_bChannelRequiresHalt = 0x7ed; // bool
		constexpr uint32_t m_bAutoPurchaseItems = 0x7ee; // bool
		constexpr uint32_t m_bDisableHUDErrorMessages = 0x7ef; // bool
		constexpr uint32_t m_iMouseDragStartX = 0x7f0; // int32
		constexpr uint32_t m_iMouseDragStartY = 0x7f4; // int32
		constexpr uint32_t m_nWeatherType = 0x7f8; // int32
		constexpr uint32_t m_bDynamicWeatherSystemActive = 0x7fc; // bool
		constexpr uint32_t m_bDynamicSoundHandled = 0x7fd; // bool
		constexpr uint32_t m_flDynamicWeatherNextSwitchTime = 0x800; // GameTime_t
		constexpr uint32_t m_flDynamicWeatherScaleFinishedTime = 0x804; // GameTime_t
		constexpr uint32_t m_flDynamicWeatherIntensity = 0x808; // float32
		constexpr uint32_t m_nXPRangeFXIndex = 0x80c; // ParticleIndex_t
		constexpr uint32_t m_nVisionRangeFXIndex = 0x810; // ParticleIndex_t
		constexpr uint32_t m_nSelectedControlGroup = 0x814; // int32
		constexpr uint32_t m_nCachedCoachedTeam = 0x818; // int32
		constexpr uint32_t m_hActiveAbility = 0x81c; // CHandle< C_DOTABaseAbility >
		constexpr uint32_t m_unitorders = 0x820; // CUtlVector< CUnitOrders >
		constexpr uint32_t m_nOutgoingOrderSequenceNumber = 0x838; // int32
		constexpr uint32_t m_nServerOrderSequenceNumber = 0x83c; // int32
		constexpr uint32_t m_nLastSentOutgoingOrderSequenceNumber = 0x840; // int32
		constexpr uint32_t m_nSelectedUnits = 0x848; // CUtlVector< CEntityIndex >
		constexpr uint32_t m_nWaypoints = 0x860; // CUtlVector< ParticleIndex_t >
		constexpr uint32_t m_iActions = 0x878; // int32
		constexpr uint32_t m_hQueryUnit = 0x87c; // CHandle< C_DOTA_BaseNPC >
		constexpr uint32_t m_bInQuery = 0x880; // bool
		constexpr uint32_t m_bSelectionChangedInDataUpdate = 0x881; // bool
		constexpr uint32_t m_flQueryInhibitingActionTime = 0x8e8; // GameTime_t
		constexpr uint32_t m_flQueryInhibitDuration = 0x8ec; // float32
		constexpr uint32_t m_RingedEntities = 0x8f0; // CUtlVector< CHandle< C_BaseEntity > >
		constexpr uint32_t m_ActiveRingOwners = 0x908; // CUtlVector< CHandle< C_BaseEntity > >
		constexpr uint32_t m_bOverridingQuery = 0x920; // bool
		constexpr uint32_t m_flLastAutoRepeatTime = 0x928; // float32
		constexpr uint32_t m_flConsumeDoubleclickTime = 0x92c; // float32
		constexpr uint32_t m_LightInfoWeatherEffect = 0x930; // CUtlString
		constexpr uint32_t m_bPreviousWasLightInfoWeather = 0x938; // bool
		constexpr uint32_t m_MapDefaultWeatherEffect = 0x940; // CUtlString
		constexpr uint32_t m_bMapUsesDynamicWeather = 0x948; // bool
		constexpr uint32_t m_nCastRangeEffectCreationRadius = 0x970; // int32
		constexpr uint32_t m_vecSuggestedWardLocationEffects = 0x990; // CUtlVector< ParticleIndex_t >
		constexpr uint32_t m_pSmartCastNPC = 0x9a8; // C_DOTA_BaseNPC*
		constexpr uint32_t m_nTeamSprayParticleIndex = 0x9b0; // ParticleIndex_t
		constexpr uint32_t m_bIsNextCastOrderFromMouseClick = 0x9b4; // bool
		constexpr uint32_t m_iCursor = 0x9e8; // int32[2]
		constexpr uint32_t m_iSpectatorClickBehavior = 0x9f0; // int32
		constexpr uint32_t m_flAspectRatio = 0x9f4; // float32
		constexpr uint32_t m_hSpectatorQueryUnit = 0x9f8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_iStatsPanel = 0x9fc; // int32
		constexpr uint32_t m_iShopPanel = 0xa00; // int32
		constexpr uint32_t m_iShopViewMode = 0xa04; // ShopItemViewMode_t
		constexpr uint32_t m_iStatsDropdownCategory = 0xa08; // int32
		constexpr uint32_t m_iStatsDropdownSort = 0xa0c; // int32
		constexpr uint32_t m_szShopString = 0xa10; // char[64]
		constexpr uint32_t m_vecClientQuickBuyState = 0xa50; // C_UtlVectorEmbeddedNetworkVar< ClientQuickBuyItemState >
		constexpr uint32_t m_bInShowCaseMode = 0xaa0; // bool
		constexpr uint32_t m_flCameraZoomAmount = 0xaa4; // float32
		constexpr uint32_t m_iHighPriorityScore = 0xaa8; // int32
		constexpr uint32_t m_quickBuyItems = 0xaac; // AbilityID_t[9]
		constexpr uint32_t m_quickBuyIsPurchasable = 0xad0; // bool[9]
		constexpr uint32_t m_flFrameTime = 0xadc; // float32
		constexpr uint32_t m_flFrameTimeStdDev = 0xae0; // float32
		constexpr uint32_t m_flUnfilteredFrameTime = 0xae4; // float32
		constexpr uint32_t m_NeutralCampAlarms = 0xae8; // CUtlVector< NeutralCampStackPullAlarm_t >
		constexpr uint32_t m_iPrevCursor = 0xb00; // int32[2]
		constexpr uint32_t m_iPositionHistoryTail = 0xba8; // int32
		constexpr uint32_t m_iMusicStatus = 0xbac; // int32
		constexpr uint32_t m_iPreviousMusicStatus = 0xbb0; // int32
		constexpr uint32_t m_bRequestedInventory = 0xbb4; // bool
		constexpr uint32_t m_flMusicOperatorVals = 0xbb8; // float32[3]
		constexpr uint32_t m_iMusicOperatorVals = 0xbc4; // int32[4]
		constexpr uint32_t m_ControlGroups = 0xbd8; // CUtlVector< sControlGroupElem >[10]
		constexpr uint32_t m_pkvControlGroupKV = 0xcc8; // KeyValues*
		constexpr uint32_t m_flAltHeldStartTime = 0xd28; // float32
	}
	namespace CSkeletonInstance {
		constexpr uint32_t m_bDirtyMotionType = 0x0; // bitfield:1
		constexpr uint32_t m_modelState = 0x160; // CModelState
		constexpr uint32_t m_bIsAnimationEnabled = 0x390; // bool
		constexpr uint32_t m_bUseParentRenderBounds = 0x391; // bool
		constexpr uint32_t m_bDisableSolidCollisionsForHierarchy = 0x392; // bool
		constexpr uint32_t m_materialGroup = 0x394; // CUtlStringToken
		constexpr uint32_t m_nHitboxSet = 0x398; // uint8
	}
	namespace CGameSceneNode {
		constexpr uint32_t m_bDirtyHierarchy = 0x0; // bitfield:1
		constexpr uint32_t m_nodeToWorld = 0x10; // CTransform
		constexpr uint32_t m_pOwner = 0x30; // CEntityInstance*
		constexpr uint32_t m_pParent = 0x38; // CGameSceneNode*
		constexpr uint32_t m_pChild = 0x40; // CGameSceneNode*
		constexpr uint32_t m_pNextSibling = 0x48; // CGameSceneNode*
		constexpr uint32_t m_hParent = 0x70; // CGameSceneNodeHandle
		constexpr uint32_t m_vecOrigin = 0x80; // CNetworkOriginCellCoordQuantizedVector
		constexpr uint32_t m_angRotation = 0xb8; // QAngle
		constexpr uint32_t m_flScale = 0xc4; // float32
		constexpr uint32_t m_vecAbsOrigin = 0xc8; // Vector
		constexpr uint32_t m_angAbsRotation = 0xd4; // QAngle
		constexpr uint32_t m_flAbsScale = 0xe0; // float32
		constexpr uint32_t m_nParentAttachmentOrBone = 0xe4; // int16
		constexpr uint32_t m_bDebugAbsOriginChanges = 0xe6; // bool
		constexpr uint32_t m_bDormant = 0xe7; // bool
		constexpr uint32_t m_bForceParentToBeNetworked = 0xe8; // bool
		constexpr uint32_t m_nHierarchicalDepth = 0xeb; // uint8
		constexpr uint32_t m_nHierarchyType = 0xec; // uint8
		constexpr uint32_t m_nDoNotSetAnimTimeInInvalidatePhysicsCount = 0xed; // uint8
		constexpr uint32_t m_name = 0xf0; // CUtlStringToken
		constexpr uint32_t m_hierarchyAttachName = 0x130; // CUtlStringToken
		constexpr uint32_t m_flZOffset = 0x134; // float32
		constexpr uint32_t m_vRenderOrigin = 0x138; // Vector
	}
	namespace CModelState {
		constexpr uint32_t m_hModel = 0xa0; // CStrongHandle< InfoForResourceTypeCModel >
		constexpr uint32_t m_ModelName = 0xa8; // CUtlSymbolLarge
		constexpr uint32_t m_bClientClothCreationSuppressed = 0xe8; // bool
		constexpr uint32_t m_MeshGroupMask = 0x180; // uint64
		constexpr uint32_t m_nIdealMotionType = 0x222; // int8
		constexpr uint32_t m_nForceLOD = 0x223; // int8
		constexpr uint32_t m_nClothUpdateFlags = 0x224; // int8
	}
	namespace C_DOTA_PlayerResource {
		constexpr uint32_t m_bWasDataUpdateCreated = 0x548; // bool
		constexpr uint32_t m_vecPlayerTeamData = 0x550; // C_UtlVectorEmbeddedNetworkVar< PlayerResourcePlayerTeamData_t >
		constexpr uint32_t m_vecPlayerData = 0x5a0; // C_UtlVectorEmbeddedNetworkVar< PlayerResourcePlayerData_t >
		constexpr uint32_t m_vecBrodcasterData = 0x5f0; // C_UtlVectorEmbeddedNetworkVar< PlayerResourceBroadcasterData_t >
		constexpr uint32_t m_vecEventsForDisplay = 0x640; // C_NetworkUtlVectorBase< uint32 >
		constexpr uint32_t m_nPrimaryEventIndex = 0x658; // int8
		constexpr uint32_t m_nObsoleteEventIDAssociatedWithEventData = 0x65c; // uint32
		constexpr uint32_t m_playerIDToPlayer = 0x660; // CHandle< C_BaseEntity >[64]
		constexpr uint32_t m_iszName = 0x760; // CUtlSymbolLarge[64]
		constexpr uint32_t m_iszHTMLSafeName = 0x960; // CUtlSymbolLarge[64]
		constexpr uint32_t m_iszFilteredHTMLSafeName = 0xb60; // CUtlSymbolLarge[64]
		constexpr uint32_t m_bDirtySuggestedItems = 0x2560; // bool
		constexpr uint32_t m_bDirtyEstimatedMatchDuration = 0x2561; // bool
		constexpr uint32_t m_bDirtySelection = 0x2562; // bool
		constexpr uint32_t m_bHasWorldTreesChanged = 0x2563; // bool
		constexpr uint32_t m_bWorldTreeModelsChanged = 0x2564; // bool
		constexpr uint32_t m_bSwapWillingness = 0x2565; // bool[24]
		constexpr uint32_t m_hTeamCouriers = 0x25c0; // CUtlVector< CHandle< C_DOTA_Unit_Courier > >[15]
		constexpr uint32_t m_hPlayerCouriers = 0x2728; // CUtlVector< CHandle< C_DOTA_Unit_Courier > >[64]
		constexpr uint32_t m_vecOnstageHomeTeams = 0x2d28; // CUtlVector< uint32 >
		constexpr uint32_t m_pPlayerIDToOnstageSlot = 0x2d40; // PlayerSeatAssignment_t*[24]
		constexpr uint32_t m_vecOnstagePlayerSeats = 0x2e00; // CUtlVector< PlayerSeatAssignment_t >
		constexpr uint32_t m_nEventNPCReplaced = 0x2e18; // int32
		constexpr uint32_t m_nEventPlayerInfo = 0x2e1c; // int32
		constexpr uint32_t m_nInventoryUpdated = 0x2e20; // int32
	}
	namespace PlayerResourcePlayerTeamData_t {
		constexpr uint32_t m_ThreatLevelInfos = 0x30; // C_UtlVectorEmbeddedNetworkVar< DOTAThreatLevelInfo_t >
		constexpr uint32_t m_nSelectedHeroID = 0x80; // int32
		constexpr uint32_t m_iKills = 0x84; // int32
		constexpr uint32_t m_iAssists = 0x88; // int32
		constexpr uint32_t m_iDeaths = 0x8c; // int32
		constexpr uint32_t m_iStreak = 0x90; // int32
		constexpr uint32_t m_iLevel = 0x94; // int32
		constexpr uint32_t m_iCustomIntParam = 0x98; // int32
		constexpr uint32_t m_iRespawnSeconds = 0x9c; // int32
		constexpr uint32_t m_flLastBuybackTime = 0xa0; // GameTime_t
		constexpr uint32_t m_iLastBuybackTime_Obsolete = 0xa4; // int32
		constexpr uint32_t m_hSelectedHero = 0xa8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_bAFK = 0xac; // bool
		constexpr uint32_t m_nSuggestedHeroes = 0xb0; // int32[4]
		constexpr uint32_t m_bBanSuggestedHeroes = 0xc0; // bool[4]
		constexpr uint32_t m_iTimedRewardDrops = 0xc4; // item_definition_index_t
		constexpr uint32_t m_iTimedRewardDropOrigins = 0xc8; // int32
		constexpr uint32_t m_iTimedRewardCrates = 0xcc; // item_definition_index_t
		constexpr uint32_t m_iTimedRewardEvents = 0xd0; // item_definition_index_t
		constexpr uint32_t m_unCompendiumLevel = 0xd4; // uint16
		constexpr uint32_t m_bCanRepick = 0xd6; // bool
		constexpr uint32_t m_bCanEarnRewards = 0xd7; // bool
		constexpr uint32_t m_bHasRandomed = 0xd8; // bool
		constexpr uint32_t m_nRandomedHeroID = 0xdc; // int32
		constexpr uint32_t m_bBattleBonusActive = 0xe0; // bool
		constexpr uint32_t m_iBattleBonusRate = 0xe2; // uint16
		constexpr uint32_t m_iCustomBuybackCost = 0xe4; // int32
		constexpr uint32_t m_CustomPlayerColor = 0xe8; // Color
		constexpr uint32_t m_bQualifiesForPAContractReward = 0xec; // bool
		constexpr uint32_t m_bHasPredictedVictory = 0xed; // bool
		constexpr uint32_t m_UnitShareMasks = 0xf0; // int32
		constexpr uint32_t m_iTeamSlot = 0xf4; // int32
		constexpr uint32_t m_iBattleCupWinStreak = 0xf8; // uint8
		constexpr uint32_t m_iBattleCupWinDate = 0x100; // uint64
		constexpr uint32_t m_iBattleCupSkillLevel = 0x108; // uint16
		constexpr uint32_t m_iBattleCupTeamID = 0x10c; // uint32
		constexpr uint32_t m_iBattleCupTournamentID = 0x110; // uint32
		constexpr uint32_t m_iBattleCupDivision = 0x114; // uint8
		constexpr uint32_t m_flTeamFightParticipation = 0x118; // float32
		constexpr uint32_t m_iFirstBloodClaimed = 0x11c; // int32
		constexpr uint32_t m_iFirstBloodGiven = 0x120; // int32
		constexpr uint32_t m_unPickOrder = 0x124; // uint32
		constexpr uint32_t m_flTimeOfLastSaluteSent = 0x128; // GameTime_t
		constexpr uint32_t m_vecPlayerEventData = 0x130; // C_UtlVectorEmbeddedNetworkVar< PlayerResourcePlayerEventData_t >
		constexpr uint32_t m_unSelectedHeroBadgeXP = 0x180; // uint32
		constexpr uint32_t m_iBountyRunes = 0x184; // uint8
		constexpr uint32_t m_iPowerRunes = 0x185; // uint8
		constexpr uint32_t m_iWaterRunes = 0x186; // uint8
		constexpr uint32_t m_iOutpostsCaptured = 0x187; // uint8
		constexpr uint32_t m_unGuildTier = 0x188; // uint8
		constexpr uint32_t m_unGuildLevel = 0x18a; // uint16
		constexpr uint32_t m_unGuildPrimaryColor = 0x18c; // uint8
		constexpr uint32_t m_unGuildSecondaryColor = 0x18d; // uint8
		constexpr uint32_t m_unGuildPattern = 0x18e; // uint8
		constexpr uint32_t m_unGuildLogo = 0x190; // uint64
		constexpr uint32_t m_unGuildFlags = 0x198; // uint32
		constexpr uint32_t m_bIsPartyGuild = 0x19c; // bool
		constexpr uint32_t m_unGuildID = 0x1a0; // GuildID_t
		constexpr uint32_t m_unHeroStickerDefIndex = 0x1a4; // item_definition_index_t
		constexpr uint32_t m_eHeroStickerQuality = 0x1a8; // uint8
		constexpr uint32_t m_eLaneSelectionFlags = 0x1a9; // uint8
		constexpr uint32_t m_nPlayerDraftPreferredRoles = 0x1aa; // uint8
		constexpr uint32_t m_nPlayerDraftPreferredTeam = 0x1ab; // int8
		constexpr uint32_t m_iObsoleteEventPoints = 0x1ac; // uint32
		constexpr uint32_t m_iObsoleteEventPremiumPoints = 0x1b0; // uint32
		constexpr uint32_t m_iObsoleteEventWagerTokensRemaining = 0x1b4; // uint32
		constexpr uint32_t m_iObsoleteEventWagerTokensMax = 0x1b8; // uint32
		constexpr uint32_t m_iObsoleteEventEffectsMask = 0x1bc; // uint32
		constexpr uint32_t m_iObsoleteEventRanks = 0x1c0; // uint16
		constexpr uint32_t m_bObsoleteIsEventOwned = 0x1c2; // bool
		constexpr uint32_t m_iObsoleteRankWagersAvailable = 0x1c4; // uint32
		constexpr uint32_t m_iObsoleteRankWagersMax = 0x1c8; // uint32
		constexpr uint32_t m_iObsoleteEventPointAdjustmentsRemaining = 0x1cc; // uint32
		constexpr uint32_t m_iObsoleteAvailableSalutes = 0x1d0; // uint32
		constexpr uint32_t m_iObsoleteSaluteAmounts = 0x1d4; // uint32
	}
	namespace C_DOTAGamerules {
		constexpr uint32_t __m_pChainEntity = 0x8; // CNetworkVarChainer
		constexpr uint32_t m_nTotalPausedTicks = 0x30; // int32
		constexpr uint32_t m_nPauseStartTick = 0x34; // int32
		constexpr uint32_t m_nRuneCycle = 0x38; // int32
		constexpr uint32_t m_bGamePaused = 0x3c; // bool
		constexpr uint32_t m_iMiscHeroPickCounter = 0x40; // int32
		constexpr uint32_t m_hEndGameCinematicEntity = 0x44; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hOverlayHealthBarUnit = 0x48; // CHandle< C_DOTA_BaseNPC >
		constexpr uint32_t m_nOverlayHealthBarType = 0x4c; // int32
		constexpr uint32_t m_bIsInCinematicMode = 0x50; // bool
		constexpr uint32_t m_bIsInClientSideCinematicMode = 0x51; // bool
		constexpr uint32_t m_bFreeCourierMode = 0x52; // bool
		constexpr uint32_t m_nStartingGold = 0x54; // int32
		constexpr uint32_t m_nGoldPerTick = 0x58; // int32
		constexpr uint32_t m_flGoldTickTime = 0x5c; // float32
		constexpr uint32_t m_bItemWhiteListChanged = 0x60; // bool
		constexpr uint32_t m_bEnableSuggestAbilities = 0x61; // bool
		constexpr uint32_t m_bEnableSuggestItems = 0x62; // bool
		constexpr uint32_t m_unFanfareGoodGuys = 0x64; // uint32
		constexpr uint32_t m_unFanfareBadGuys = 0x68; // uint32
		constexpr uint32_t m_iMapType = 0x6c; // int32
		constexpr uint32_t m_nServerGameState = 0x70; // int32
		constexpr uint32_t m_nServerHeroPickState = 0x74; // DOTA_HeroPickState
		constexpr uint32_t m_nGameState = 0x78; // int32
		constexpr uint32_t m_nHeroPickState = 0x7c; // DOTA_HeroPickState
		constexpr uint32_t m_bAlternateHeroGridsEnabled = 0x80; // bool
		constexpr uint32_t m_flStateTransitionTime = 0x84; // GameTime_t
		constexpr uint32_t m_flOverride_dota_hero_selection_time = 0x88; // float32
		constexpr uint32_t m_flOverride_dota_pregame_time = 0x8c; // float32
		constexpr uint32_t m_flOverride_dota_postgame_time = 0x90; // float32
		constexpr uint32_t m_flOverride_dota_strategy_time = 0x94; // float32
		constexpr uint32_t m_flOverride_dota_team_showcase_duration = 0x98; // float32
		constexpr uint32_t m_flOverride_dota_rune_spawn_time = 0x9c; // float32
		constexpr uint32_t m_flShowcaseTime = 0xa0; // float32[15]
		constexpr uint32_t m_flNeutralInitialSpawnOffset = 0xdc; // float32
		constexpr uint32_t m_iGameMode = 0xe0; // int32
		constexpr uint32_t m_hGameModeEntity = 0xe4; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hCustomHeroPickRulesEntity = 0xe8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_flHeroPickStateTransitionTime = 0xec; // GameTime_t
		constexpr uint32_t m_iPlayerIDsInControl = 0xf0; // uint64
		constexpr uint32_t m_bSameHeroSelectionEnabled = 0xf8; // bool
		constexpr uint32_t m_bUseCustomHeroXPValue = 0xf9; // bool
		constexpr uint32_t m_bUseBaseGoldBountyOnHeroes = 0xfa; // bool
		constexpr uint32_t m_bUseUniversalShopMode = 0xfb; // bool
		constexpr uint32_t m_bHideKillMessageHeaders = 0xfc; // bool
		constexpr uint32_t m_flHeroMinimapIconScale = 0x100; // float32
		constexpr uint32_t m_flCreepMinimapIconScale = 0x104; // float32
		constexpr uint32_t m_bCreepSpawningEnabled = 0x108; // bool
		constexpr uint32_t m_flRuneMinimapIconScale = 0x10c; // float32
		constexpr uint32_t m_CustomVictoryMessage = 0x110; // char[256]
		constexpr uint32_t m_flCustomGameEndDelay = 0x210; // float32
		constexpr uint32_t m_flCustomGameSetupAutoLaunchDelay = 0x214; // float32
		constexpr uint32_t m_flCustomGameSetupTimeout = 0x218; // float32
		constexpr uint32_t m_flCustomVictoryMessageDuration = 0x21c; // float32
		constexpr uint32_t m_flHeroSelectPenaltyTime = 0x220; // float32
		constexpr uint32_t m_bCustomGameSetupAutoLaunchEnabled = 0x224; // bool
		constexpr uint32_t m_bCustomGameTeamSelectionLocked = 0x225; // bool
		constexpr uint32_t m_bCustomGameEnablePickRules = 0x226; // bool
		constexpr uint32_t m_bCustomGameAllowHeroPickMusic = 0x227; // bool
		constexpr uint32_t m_bCustomGameAllowMusicAtGameStart = 0x228; // bool
		constexpr uint32_t m_bCustomGameAllowBattleMusic = 0x229; // bool
		constexpr uint32_t m_bCustomGameDisableIK = 0x22a; // bool
		constexpr uint32_t m_bCustomGameAllowSecondaryAbilitiesOnOtherUnits = 0x22b; // bool
		constexpr uint32_t m_iCMModePickBanOrder = 0x22c; // int32
		constexpr uint32_t m_iCDModePickBanOrder = 0x230; // int32
		constexpr uint32_t m_nGGTeam = 0x234; // int32
		constexpr uint32_t m_flGGEndsAtTime = 0x238; // GameTime_t
		constexpr uint32_t m_bGGCalled = 0x23c; // bool
		constexpr uint32_t m_bWhiteListEnabled = 0x23d; // bool
		constexpr uint32_t m_bItemWhiteList = 0x240; // uint64[4]
		constexpr uint32_t m_nLastHitUIMode = 0x260; // int32
		constexpr uint32_t m_bHUDTimerTutorialMode = 0x264; // bool
		constexpr uint32_t m_HeroPickMiscTimer = 0x268; // CountdownTimer
		constexpr uint32_t m_ExtraTimeTimer = 0x280; // CountdownTimer
		constexpr uint32_t m_fExtraTimeRemaining = 0x298; // float32[2]
		constexpr uint32_t m_bHeroRespawnEnabled = 0x2a0; // bool
		constexpr uint32_t m_bIsRandomingEnabled = 0x2a1; // bool
		constexpr uint32_t m_iCaptainPlayerIDs = 0x2a4; // PlayerID_t[2]
		constexpr uint32_t m_BannedHeroes = 0x2ac; // int32[24]
		constexpr uint32_t m_SelectedHeroes = 0x30c; // int32[24]
		constexpr uint32_t m_iActiveTeam = 0x36c; // int32
		constexpr uint32_t m_iStartingTeam = 0x370; // int32
		constexpr uint32_t m_iPenaltyLevelRadiant = 0x374; // int32
		constexpr uint32_t m_iPenaltyLevelDire = 0x378; // int32
		constexpr uint32_t m_bIsLoadingScenario = 0x37c; // bool
		constexpr uint32_t m_vecNewBannedHeroes = 0x380; // C_NetworkUtlVectorBase< int32 >
		constexpr uint32_t m_vecWhitelistedHeroes = 0x398; // C_NetworkUtlVectorBase< int32 >
		constexpr uint32_t m_vecBlacklistedHeroes = 0x3b0; // C_NetworkUtlVectorBase< int32 >
		constexpr uint32_t m_bHideBlacklistedHeroes = 0x3c8; // bool
		constexpr uint32_t m_nSeriesType = 0x3cc; // int32
		constexpr uint32_t m_nRadiantSeriesWins = 0x3d0; // int32
		constexpr uint32_t m_nDireSeriesWins = 0x3d4; // int32
		constexpr uint32_t m_vecAvailableHerosPerPlayerID = 0x3d8; // C_UtlVectorEmbeddedNetworkVar< CHeroesPerPlayer >
		constexpr uint32_t m_vecLockedHerosByPlayerID = 0x428; // C_UtlVectorEmbeddedNetworkVar< CHeroesPerPlayer >
		constexpr uint32_t m_vecDisabledRandomHerosByPlayerID = 0x478; // C_UtlVectorEmbeddedNetworkVar< CHeroesPerPlayer >
		constexpr uint32_t m_CustomGameForceSelectHero = 0x4c8; // int32[24]
		constexpr uint32_t m_flGoldTime = 0x528; // float32
		constexpr uint32_t m_flXPTime = 0x52c; // float32
		constexpr uint32_t m_flCreepSpawntime = 0x530; // GameTime_t
		constexpr uint32_t m_flAnnounceStartTime = 0x534; // float32
		constexpr uint32_t m_iGoodTomeCount = 0x538; // int32
		constexpr uint32_t m_iBadTomeCount = 0x53c; // int32
		constexpr uint32_t m_flPreGameStartTime = 0x540; // GameTime_t
		constexpr uint32_t m_flGameStartTime = 0x544; // GameTime_t
		constexpr uint32_t m_flGameEndTime = 0x548; // GameTime_t
		constexpr uint32_t m_flGameLoadTime = 0x54c; // float32
		constexpr uint32_t m_iCustomGameScore = 0x550; // int32[2]
		constexpr uint32_t m_nCustomGameDifficulty = 0x558; // int32
		constexpr uint32_t m_bEnemyModifiersEnabled = 0x55c; // bool
		constexpr uint32_t m_iWaves = 0x560; // int32
		constexpr uint32_t m_iCreepUpgradeState = 0x564; // int32
		constexpr uint32_t m_fGoodGlyphCooldown = 0x568; // GameTime_t
		constexpr uint32_t m_fBadGlyphCooldown = 0x56c; // GameTime_t
		constexpr uint32_t m_flGlyphCooldowns = 0x570; // GameTime_t[15]
		constexpr uint32_t m_fGoodRadarCooldown = 0x5ac; // GameTime_t
		constexpr uint32_t m_fBadRadarCooldown = 0x5b0; // GameTime_t
		constexpr uint32_t m_flRadarCooldowns = 0x5b4; // GameTime_t[15]
		constexpr uint32_t m_iGoodRadarCharges = 0x5f0; // int32
		constexpr uint32_t m_iBadRadarCharges = 0x5f4; // int32
		constexpr uint32_t m_iRadarCharges = 0x5f8; // int32[15]
		constexpr uint32_t m_flOutpostTimes = 0x634; // float32[24]
		constexpr uint32_t m_bIsNightstalkerNight = 0x694; // bool
		constexpr uint32_t m_bIsTemporaryNight = 0x695; // bool
		constexpr uint32_t m_bIsTemporaryDay = 0x696; // bool
		constexpr uint32_t m_nRiverType = 0x698; // int32
		constexpr uint32_t m_nTeamFeaturedPlayerID = 0x69c; // PlayerID_t[15]
		constexpr uint32_t m_nTeamVersusScreen = 0x6d8; // item_definition_index_t[15]
		constexpr uint32_t m_flGoldRedistributeTime = 0x714; // float32
		constexpr uint32_t m_nGoldToRedistribute = 0x718; // int32[2]
		constexpr uint32_t m_flNextPreGameThink = 0x720; // GameTime_t
		constexpr uint32_t m_flNextAllDraftGoldThink = 0x724; // GameTime_t
		constexpr uint32_t m_flTimeEnteredState = 0x728; // float64
		constexpr uint32_t m_unRiverAccountID = 0x730; // uint32
		constexpr uint32_t m_ulRiverItemID = 0x738; // itemid_t
		constexpr uint32_t m_vecItemStockInfo = 0x780; // C_UtlVectorEmbeddedNetworkVar< CDOTA_ItemStockInfo >
		constexpr uint32_t m_AssassinMiniGameNetData = 0x7d0; // DOTA_AssassinMinigameNetworkState
		constexpr uint32_t m_nGameWinner = 0x7e0; // int32
		constexpr uint32_t m_unMatchID64 = 0x7e8; // MatchID_t
		constexpr uint32_t m_bMatchSignoutComplete = 0x7f0; // bool
		constexpr uint32_t m_hSideShop1 = 0x7f4; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hSideShop2 = 0x7f8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hSecretShop1 = 0x7fc; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hSecretShop2 = 0x800; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hTeamFountains = 0x804; // CHandle< C_BaseEntity >[15]
		constexpr uint32_t m_hTeamForts = 0x840; // CHandle< C_BaseEntity >[15]
		constexpr uint32_t m_hTeamShops = 0x87c; // CHandle< C_BaseEntity >[15]
		constexpr uint32_t m_hAnnouncerGood = 0x8b8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerBad = 0x8bc; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerSpectator = 0x8c0; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerGood_KillingSpree = 0x8c4; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerBad_KillingSpree = 0x8c8; // CHandle< C_BaseEntity >
		constexpr uint32_t m_hAnnouncerSpectator_KillingSpree = 0x8cc; // CHandle< C_BaseEntity >
		constexpr uint32_t m_arrTier1TowerDestroyed = 0x8d0; // bool[15]
		constexpr uint32_t m_arrTier2TowerDestroyed = 0x8df; // bool[15]
		constexpr uint32_t m_arrTier3TowerDestroyed = 0x8ee; // bool[15]
		constexpr uint32_t m_bTier1TowerDestroyed = 0x8fd; // bool
		constexpr uint32_t m_bTier2TowerDestroyed = 0x8fe; // bool
		constexpr uint32_t m_bTier3TowerDestroyed = 0x8ff; // bool
		constexpr uint32_t m_fTimeOfDay = 0x900; // float32
		constexpr uint32_t m_iNetTimeOfDay = 0x904; // int32
		constexpr uint32_t m_nLoadedPlayers = 0x908; // int32
		constexpr uint32_t m_nExpectedPlayers = 0x90c; // int32
		constexpr uint32_t m_iMinimapDebugGridState = 0x918; // int32
		constexpr uint32_t m_iFoWFrameNumber = 0x998; // int32
		constexpr uint32_t m_vWeatherWindDirection = 0x99c; // Vector
		constexpr uint32_t m_vecRequiredPlaytestHeroesStorage = 0x9a8; // int32[24]
		constexpr uint32_t m_vecRecommendedPlaytestHeroesStorage = 0xa08; // int32[24]
		constexpr uint32_t m_bAllRequiredPlaytestHeroesPicked = 0xa68; // bool
		constexpr uint32_t m_nLastPlaytestPickPhase = 0xa6c; // int32
		constexpr uint32_t m_nCustomGameFowTeamCount = 0xa70; // int32
		constexpr uint32_t m_bUseAlternateABRules = 0xa74; // bool
		constexpr uint32_t m_bLobbyIsAssociatedWithGame = 0xa75; // bool
		constexpr uint32_t m_BotDebugTimer = 0xa78; // CountdownTimer
		constexpr uint32_t m_BotDebugPushLane = 0xa90; // uint8[18]
		constexpr uint32_t m_BotDebugDefendLane = 0xaa2; // uint8[18]
		constexpr uint32_t m_BotDebugFarmLane = 0xab4; // uint8[6]
		constexpr uint32_t m_BotDebugRoam = 0xaba; // uint8[8]
		constexpr uint32_t m_hBotDebugRoamTarget = 0xac4; // CHandle< C_BaseEntity >[2]
		constexpr uint32_t m_BotDebugRoshan = 0xacc; // uint8[2]
		constexpr uint32_t m_nRoshanRespawnPhase = 0xad0; // ERoshanSpawnPhase
		constexpr uint32_t m_flRoshanRespawnPhaseEndTime = 0xad4; // GameTime_t
		constexpr uint32_t m_AbilityDraftAbilities = 0xad8; // C_UtlVectorEmbeddedNetworkVar< CDOTA_AbilityDraftAbilityState >
		constexpr uint32_t m_bAbilityDraftCurrentPlayerHasPicked = 0xb28; // bool
		constexpr uint32_t m_nAbilityDraftPlayerTracker = 0xb2c; // int32
		constexpr uint32_t m_nAbilityDraftRoundNumber = 0xb30; // int32
		constexpr uint32_t m_nAbilityDraftAdvanceSteps = 0xb34; // int32
		constexpr uint32_t m_nAbilityDraftPhase = 0xb38; // int32
		constexpr uint32_t m_nAbilityDraftHeroesChosen = 0xb3c; // int32[13]
		constexpr uint32_t m_bIsPlayerDraft = 0xb70; // bool
		constexpr uint32_t m_ePlayerDraftState = 0xb74; // DOTA_PlayerDraftState
		constexpr uint32_t m_vecPlayerDraftPickOrder = 0xb78; // C_NetworkUtlVectorBase< uint8 >
		constexpr uint32_t m_nPlayerDraftPick = 0xb90; // int32
		constexpr uint32_t m_nPlayerDraftActiveTeam = 0xb94; // int32
		constexpr uint32_t m_flPlayerDraftTimeBank = 0xb98; // float32[2]
		constexpr uint32_t m_vecARDMHeroes = 0xba0; // CUtlVector< KeyValues* >[2]
		constexpr uint32_t m_nARDMHeroesPrecached = 0xbd0; // int32
		constexpr uint32_t m_fLastARDMPrecache = 0xbd4; // float32
		constexpr uint32_t m_nAllDraftPhase = 0xbd8; // int32
		constexpr uint32_t m_bAllDraftRadiantFirst = 0xbdc; // bool
		constexpr uint32_t m_bAllowOverrideVPK = 0xbdd; // bool
		constexpr uint32_t m_nARDMHeroesRemaining = 0xbe0; // int32[2]
		constexpr uint32_t m_bUpdateHeroStatues = 0xbe8; // bool
		constexpr uint32_t m_bExperimentalGameplay = 0xc00; // bool
		constexpr uint32_t m_vecPlayerMMR = 0xc40; // CUtlVector< int32 >
		constexpr uint32_t m_lobbyType = 0xc58; // uint32
		constexpr uint32_t m_lobbyLeagueID = 0xc5c; // LeagueID_t
		constexpr uint32_t m_lobbyGameName = 0xc60; // char[256]
		constexpr uint32_t m_vecHeroStatueLiked = 0xd60; // C_UtlVectorEmbeddedNetworkVar< CHeroStatueLiked >
		constexpr uint32_t m_CustomGameTeamMaxPlayers = 0xdb0; // int32[15]
		constexpr uint32_t m_iMutations = 0xdec; // int32[5]
		constexpr uint32_t m_vecIngameEvents = 0xe00; // C_NetworkUtlVectorBase< CHandle< C_IngameEvent_Base > >
		constexpr uint32_t m_nPrimaryIngameEventIndex = 0xe18; // int8
		constexpr uint32_t m_hObsoleteIngameEvent = 0xe1c; // CHandle< C_IngameEvent_Base >
		constexpr uint32_t m_nOfrendaPledges = 0xe20; // uint32
		constexpr uint32_t m_nRadiantOfrendas = 0xe24; // uint32
		constexpr uint32_t m_nDireOfrendas = 0xe28; // uint32
		constexpr uint32_t m_bOfrendaEnabled = 0xe2c; // bool
		constexpr uint32_t m_NeutralSpawnBoxes = 0xe60; // C_NetworkUtlVectorBase< NeutralSpawnBoxes_t >
		constexpr uint32_t m_RegionTriggerBoxes = 0xe78; // C_NetworkUtlVectorBase< RegionTriggerBoxes_t >
		constexpr uint32_t m_flLastPerfSampleTime = 0x1e48; // float64
		constexpr uint32_t m_flLastPerfSampleSendTime = 0x1e50; // float64
		constexpr uint32_t m_bDidSeeStrategyTime = 0x1e58; // bool
		constexpr uint32_t m_flLastUnfocusedSleepTime = 0xabb0; // float64
	}
	namespace C_DOTA_Item_Rune {
		constexpr uint32_t m_iRuneType = 0x7e0; // int32
		constexpr uint32_t m_flRuneTime = 0x7e4; // float32
		constexpr uint32_t m_nMapLocationTeam = 0x7e8; // int32
		constexpr uint32_t m_szLocation = 0x7ec; // char[512]
		constexpr uint32_t m_iOldRuneType = 0x9ec; // int32
		constexpr uint32_t m_bShowingTooltip = 0x9f0; // bool
	}
	namespace GameTime_t {
		constexpr uint32_t m_Value = 0x0; // float32
	}
	namespace C_DOTA_Item_EmptyBottle {
		constexpr uint32_t m_iStoredRuneType = 0x648; // int32
		constexpr uint32_t m_fStoredRuneTime = 0x64c; // GameTime_t
		constexpr uint32_t rune_expire_time = 0x650; // float32
	}
	namespace C_DOTAGamerulesProxy {
		constexpr uint32_t m_pGameRules = 0x538; // C_DOTAGamerules*
	}
	namespace C_DOTAWearableItem {
		constexpr uint32_t m_bOwnerModelChanged = 0xaf8; // bool
		constexpr uint32_t m_bIsGeneratingEconItem = 0xaf9; // bool
		constexpr uint32_t m_bIsItemVisibleOnGeneratedEntity = 0xafa; // bool
		constexpr uint32_t m_bHideWearableButDrawAdditionalWearables = 0xafb; // bool
		constexpr uint32_t m_hAdditionalWearable = 0xafc; // CHandle< CBaseAnimatingActivity >
		constexpr uint32_t m_hDrawWearable = 0xb00; // CHandle< C_DOTAWearableItem >
		constexpr uint32_t m_bHiddenByCombiner = 0xb04; // bool
		constexpr uint32_t m_bHiddenByEquipmentSlot = 0xb05; // bool
		constexpr uint32_t m_bIsPortrait = 0xb06; // bool
		constexpr uint32_t m_fZDelta = 0xb08; // float32
		constexpr uint32_t m_combinerMaterialOverrideList = 0xb10; // CUtlVector< CStrongHandleCopyable< InfoForResourceTypeIMaterial2 > >
		constexpr uint32_t m_bCombinerMaterialOverrideListChanged = 0xb30; // bool
		constexpr uint32_t m_bRubickFollower = 0xb31; // bool
		constexpr uint32_t m_bHasPlayerModel = 0xb32; // bool
	}
	namespace C_EconItemView {
		constexpr uint32_t m_iItemDefinitionIndex = 0x8; // item_definition_index_t
		constexpr uint32_t m_iEntityQuality = 0xc; // int32
		constexpr uint32_t m_iEntityLevel = 0x10; // uint32
		constexpr uint32_t m_iItemID = 0x18; // itemid_t
		constexpr uint32_t m_iAccountID = 0x20; // uint32
		constexpr uint32_t m_iInventoryPosition = 0x24; // uint32
		constexpr uint32_t m_bInitialized = 0x30; // bool
		constexpr uint32_t m_nOverrideStyle = 0x31; // style_index_t
		constexpr uint32_t m_bIsStoreItem = 0x32; // bool
		constexpr uint32_t m_bIsTradeItem = 0x33; // bool
		constexpr uint32_t m_bHasComputedAttachedParticles = 0x34; // bool
		constexpr uint32_t m_bHasAttachedParticles = 0x35; // bool
		constexpr uint32_t m_iEntityQuantity = 0x38; // int32
		constexpr uint32_t m_unClientFlags = 0x3c; // uint8
		constexpr uint32_t m_unOverrideOrigin = 0x40; // eEconItemOrigin
		constexpr uint32_t m_pszGrayedOutReason = 0x50; // char*
		constexpr uint32_t m_AttributeList = 0x58; // CAttributeList
	}
	namespace C_DOTA_Item_Physical {
		constexpr uint32_t m_hItem = 0x7e0; // CHandle< C_DOTA_Item >
		constexpr uint32_t m_bIsLowPriorityHoverItem = 0x7e4; // bool
		constexpr uint32_t m_hOldItem = 0x7e8; // CHandle< C_DOTA_Item >
		constexpr uint32_t m_pszParticleName = 0x7f0; // char*
		constexpr uint32_t m_nFXIndex = 0x7f8; // ParticleIndex_t
		constexpr uint32_t m_bShowingTooltip = 0x7fc; // bool
		constexpr uint32_t m_bShowingSimpleTooltip = 0x7fd; // bool
	}
	namespace CDOTA_Buff {
		constexpr uint32_t m_bIsAura = 0x0; // bitfield:1
		constexpr uint32_t m_name = 0x28; // CUtlSymbolLarge
		constexpr uint32_t m_szModifierAura = 0x38; // CUtlSymbolLarge
		constexpr uint32_t m_iSerialNumber = 0x48; // int32
		constexpr uint32_t m_iStringIndex = 0x4c; // int32
		constexpr uint32_t m_iIndex = 0x50; // int32
		constexpr uint32_t m_flCreationTime = 0x54; // GameTime_t
		constexpr uint32_t m_iCreationFrame = 0x58; // int32
		constexpr uint32_t m_flLastAppliedTime = 0x5c; // GameTime_t
		constexpr uint32_t m_flDuration = 0x60; // float32
		constexpr uint32_t m_flDieTime = 0x64; // GameTime_t
		constexpr uint32_t m_hCaster = 0x68; // CHandle< CBaseEntity >
		constexpr uint32_t m_hAbility = 0x6c; // CHandle< CBaseEntity >
		constexpr uint32_t m_hParent = 0x70; // CHandle< CBaseEntity >
		constexpr uint32_t m_hAuraOwner = 0x74; // CHandle< CBaseEntity >
		constexpr uint32_t m_iStackCount = 0x78; // int32
		constexpr uint32_t m_iAuraSearchTeam = 0x7c; // int16
		constexpr uint32_t m_iAuraSearchType = 0x7e; // int16
		constexpr uint32_t m_iAuraSearchFlags = 0x80; // int32
		constexpr uint32_t m_iAuraRadius = 0x84; // int32
		constexpr uint32_t m_iTeam = 0x88; // int32
		constexpr uint32_t m_iAttributes = 0x8c; // int32
		constexpr uint32_t m_iPaddingToMakeSchemaHappy2 = 0x90; // int16
		constexpr uint32_t m_bPurgedDestroy = 0x93; // bool
		constexpr uint32_t m_flPreviousTick = 0x94; // GameTime_t
		constexpr uint32_t m_flThinkInterval = 0x98; // float32
		constexpr uint32_t m_flThinkTimeAccumulator = 0x9c; // float32
		constexpr uint32_t m_iParticles = 0xa0; // CUtlVector< CDOTA_BuffParticle >
		constexpr uint32_t m_hAuraUnits = 0xb8; // CUtlVector< CHandle< CBaseEntity > >
		constexpr uint32_t m_hScriptScope = 0x1330; // HSCRIPT
	}
}